export const programasFormacion = [
  {
    value: "TECNÓLOGO EN GESTIÓN FINANCIERA Y DE TESORERIA",
    label: "TECNÓLOGO EN GESTIÓN FINANCIERA Y DE TESORERIA",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DEL TALENTO HUMANO",
    label: "TECNÓLOGO EN GESTIÓN DEL TALENTO HUMANO",
  },
  {
    value: "TECNÓLOGO EN GESTION ADMINISTRATIVA DEL SECTOR SALUD.",
    label: "TECNÓLOGO EN GESTION ADMINISTRATIVA DEL SECTOR SALUD.",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN BANCARIA Y DE ENTIDADES FINANCIERAS",
    label: "TECNÓLOGO EN GESTIÓN BANCARIA Y DE ENTIDADES FINANCIERAS",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN PORTUARIA",
    label: "TECNÓLOGO EN GESTIÓN PORTUARIA",
  },
  {
    value: "TECNÓLOGO EN COORDINACION DE PROCESOS LOGISTICOS",
    label: "TECNÓLOGO EN COORDINACION DE PROCESOS LOGISTICOS",
  },
  {
    value: "TECNÓLOGO EN GESTION INTEGRAL DEL TRANSPORTE",
    label: "TECNÓLOGO EN GESTION INTEGRAL DEL TRANSPORTE",
  },
  {
    value: "TECNÓLOGO EN GESTION DE OPERACIONES EN TERMINALES PORTUARIAS",
    label: "TECNÓLOGO EN GESTION DE OPERACIONES EN TERMINALES PORTUARIAS",
  },
  {
    value: "TECNÓLOGO EN GESTION DE PROYECTOS DE DESARROLLO ECONOMICO Y SOCIAL",
    label: "TECNÓLOGO EN GESTION DE PROYECTOS DE DESARROLLO ECONOMICO Y SOCIAL",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN ADMINISTRATIVA",
    label: "TECNÓLOGO EN GESTIÓN ADMINISTRATIVA",
  },
  {
    value:
      "TECNÓLOGO EN GESTIÓN INTEGRADA DE LA CALIDAD, MEDIO AMBIENTE, SEGURIDAD Y SALUD OCUPACIONAL",
    label:
      "TECNÓLOGO EN GESTIÓN INTEGRADA DE LA CALIDAD, MEDIO AMBIENTE, SEGURIDAD Y SALUD OCUPACIONAL",
  },
  {
    value: "TECNÓLOGO EN GESTION DE DESTINOS TURISTICOS.",
    label: "TECNÓLOGO EN GESTION DE DESTINOS TURISTICOS.",
  },
  {
    value: "TÉCNICO EN ADMINISTRACION DE TRANSPORTE TERRESTRE AUTOMOTOR.",
    label: "TÉCNICO EN ADMINISTRACION DE TRANSPORTE TERRESTRE AUTOMOTOR.",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE LA PROPIEDAD HORIZONTAL",
    label: "TECNÓLOGO EN GESTIÓN DE LA PROPIEDAD HORIZONTAL",
  },
  {
    value: "TECNÓLOGO EN NEGOCIACIÓN INTERNACIONAL",
    label: "TECNÓLOGO EN NEGOCIACIÓN INTERNACIONAL",
  },
  {
    value: "TECNÓLOGO EN GESTION DEL COMERCIO EXTERIOR DE BIENES Y SERVICIOS",
    label: "TECNÓLOGO EN GESTION DEL COMERCIO EXTERIOR DE BIENES Y SERVICIOS",
  },
  {
    value: "TECNÓLOGO EN ORGANIZACIÓN DE EVENTOS",
    label: "TECNÓLOGO EN ORGANIZACIÓN DE EVENTOS",
  },
  {
    value: "TÉCNICO EN OPERACIÓN DE EVENTOS",
    label: "TÉCNICO EN OPERACIÓN DE EVENTOS",
  },
  {
    value: "TECNÓLOGO EN GESTION DOCUMENTAL .",
    label: "TECNÓLOGO EN GESTION DOCUMENTAL .",
  },
  {
    value: "TECNÓLOGO EN GESTION CONTABLE Y DE INFORMACION FINANCIERA",
    label: "TECNÓLOGO EN GESTION CONTABLE Y DE INFORMACION FINANCIERA",
  },
  {
    value: "TECNÓLOGO EN GESTION CONTABLE Y FINANCIERA",
    label: "TECNÓLOGO EN GESTION CONTABLE Y FINANCIERA",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE NEGOCIOS FIDUCIARIOS",
    label: "TECNÓLOGO EN GESTIÓN DE NEGOCIOS FIDUCIARIOS",
  },
  {
    value: "TÉCNICO EN EL RIESGO CREDITICIO Y SU ADMINISTRACIÓN",
    label: "TÉCNICO EN EL RIESGO CREDITICIO Y SU ADMINISTRACIÓN",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN INTEGRAL DEL RIESGO EN SEGUROS",
    label: "TECNÓLOGO EN GESTIÓN INTEGRAL DEL RIESGO EN SEGUROS",
  },
  {
    value: "TECNÓLOGO EN GESTION DE TESORERIA Y RECURSOS FINANCIEROS",
    label: "TECNÓLOGO EN GESTION DE TESORERIA Y RECURSOS FINANCIEROS",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO PUBLICITARIO",
    label: "TECNÓLOGO EN DESARROLLO PUBLICITARIO",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE PROCESOS DE MERCADEO",
    label: "TECNÓLOGO EN DESARROLLO DE PROCESOS DE MERCADEO",
  },
  {
    value: "TECNÓLOGO EN PROCESOS PARA LA COMERCIALIZACION INTERNACIONAL",
    label: "TECNÓLOGO EN PROCESOS PARA LA COMERCIALIZACION INTERNACIONAL",
  },
  {
    value: "TÉCNICO EN CONTABILIZACION DE OPERACIONES COMERCIALES Y FINANCIERAS.",
    label: "TÉCNICO EN CONTABILIZACION DE OPERACIONES COMERCIALES Y FINANCIERAS.",
  },
  {
    value: "TÉCNICO EN SERVICIOS Y OPERACIONES MICROFINANCIERAS",
    label: "TÉCNICO EN SERVICIOS Y OPERACIONES MICROFINANCIERAS",
  },
  {
    value: "TÉCNICO EN SERVICIOS COMERCIALES Y FINANCIEROS",
    label: "TÉCNICO EN SERVICIOS COMERCIALES Y FINANCIEROS",
  },
  {
    value: "TÉCNICO EN ATENCION COMERCIAL Y OPERACION EN SEGUROS",
    label: "TÉCNICO EN ATENCION COMERCIAL Y OPERACION EN SEGUROS",
  },
  {
    value: "TÉCNICO EN NOMINA Y PRESTACIONES SOCIALES .",
    label: "TÉCNICO EN NOMINA Y PRESTACIONES SOCIALES .",
  },
  {
    value: "TÉCNICO EN ASISTENCIA ADMINISTRATIVA .",
    label: "TÉCNICO EN ASISTENCIA ADMINISTRATIVA .",
  },
  {
    value: "TÉCNICO EN EMPRENDIMIENTO Y FOMENTO EMPRESARIAL",
    label: "TÉCNICO EN EMPRENDIMIENTO Y FOMENTO EMPRESARIAL",
  },
  {
    value: "TÉCNICO EN ASISTENCIA PARA LA INTELIGENCIA EMPRESARIAL",
    label: "TÉCNICO EN ASISTENCIA PARA LA INTELIGENCIA EMPRESARIAL",
  },
  {
    value: "TÉCNICO EN ASISTENCIA EN LA FUNCION PUBLICA",
    label: "TÉCNICO EN ASISTENCIA EN LA FUNCION PUBLICA",
  },
  {
    value: "TÉCNICO EN RECURSOS HUMANOS .",
    label: "TÉCNICO EN RECURSOS HUMANOS .",
  },
  {
    value:
      "TÉCNICO EN PRESELECCION DE TALENTO HUMANO MEDIADO POR HERRAMIENTAS TIC",
    label:
      "TÉCNICO EN PRESELECCION DE TALENTO HUMANO MEDIADO POR HERRAMIENTAS TIC",
  },
  {
    value: "TÉCNICO EN ASISTENCIA EN ORGANIZACION DE ARCHIVOS .",
    label: "TÉCNICO EN ASISTENCIA EN ORGANIZACION DE ARCHIVOS .",
  },
  {
    value: "TÉCNICO EN .APOYO ADMINISTRATIVO EN SALUD.",
    label: "TÉCNICO EN .APOYO ADMINISTRATIVO EN SALUD.",
  },
  {
    value: "TÉCNICO EN OPERACIONES DE COMERCIO EXTERIOR",
    label: "TÉCNICO EN OPERACIONES DE COMERCIO EXTERIOR",
  },
  {
    value: "TÉCNICO EN SERVICIOS DIGITALES DE BIBLIOTECAS",
    label: "TÉCNICO EN SERVICIOS DIGITALES DE BIBLIOTECAS",
  },
  {
    value: "TÉCNICO EN ATENCION INTEGRAL AL CLIENTE",
    label: "TÉCNICO EN ATENCION INTEGRAL AL CLIENTE",
  },
  {
    value: "TÉCNICO EN INFORMACION Y SERVICIO AL CLIENTE",
    label: "TÉCNICO EN INFORMACION Y SERVICIO AL CLIENTE",
  },
  {
    value: "TÉCNICO EN BILINGUAL EXPERT ON BUSINESS PROCESS OUTSOURCING",
    label: "TÉCNICO EN BILINGUAL EXPERT ON BUSINESS PROCESS OUTSOURCING",
  },
  {
    value: "TÉCNICO EN MARKETING DIGITAL PARA EL SISTEMA MODA",
    label: "TÉCNICO EN MARKETING DIGITAL PARA EL SISTEMA MODA",
  },
  {
    value: "TÉCNICO EN OPERACION DE SERVICIOS OMNICANAL EN CONTACT CENTER Y BPO",
    label: "TÉCNICO EN OPERACION DE SERVICIOS OMNICANAL EN CONTACT CENTER Y BPO",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE INFORMACION DE MERCADOS",
    label: "TÉCNICO EN PROCESAMIENTO DE INFORMACION DE MERCADOS",
  },
  {
    value: "TÉCNICO EN MANEJO DE INFORMACION PARA SISTEMAS DE GESTION",
    label: "TÉCNICO EN MANEJO DE INFORMACION PARA SISTEMAS DE GESTION",
  },
  {
    value: "TÉCNICO EN SERVICIOS POSTALES Y TRANSPORTE DE MERCANCIAS",
    label: "TÉCNICO EN SERVICIOS POSTALES Y TRANSPORTE DE MERCANCIAS",
  },
  {
    value: "TÉCNICO EN OPERACIONES LOGISTICAS EN CENTROS DE DISTRIBUCION",
    label: "TÉCNICO EN OPERACIONES LOGISTICAS EN CENTROS DE DISTRIBUCION",
  },
  {
    value: "TÉCNICO EN INTEGRACION DE OPERACIONES LOGISTICAS",
    label: "TÉCNICO EN INTEGRACION DE OPERACIONES LOGISTICAS",
  },
  {
    value: "TÉCNICO EN COMPRAS Y ABASTECIMIENTO",
    label: "TÉCNICO EN COMPRAS Y ABASTECIMIENTO",
  },
  {
    value: "TÉCNICO EN SERVICE OPERATION IN BILINGUAL BPO CHANNELS",
    label: "TÉCNICO EN SERVICE OPERATION IN BILINGUAL BPO CHANNELS",
  },
  {
    value: "TÉCNICO EN MANEJO INTEGRAL DE RESIDUOS SÓLIDOS",
    label: "TÉCNICO EN MANEJO INTEGRAL DE RESIDUOS SÓLIDOS",
  },
  {
    value: "TÉCNICO EN GESTION DE LOS DERECHOS DEL CAMPESINO Y ORDENAMIENTO DE LA TERRITORIALIDAD",
    label: "TÉCNICO EN GESTION DE LOS DERECHOS DEL CAMPESINO Y ORDENAMIENTO DE LA TERRITORIALIDAD",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO Y MODELADO DE PRODUCTOS INDUSTRIALES.",
    label: "TECNÓLOGO EN DESARROLLO Y MODELADO DE PRODUCTOS INDUSTRIALES.",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO CREATIVO DE PRODUCTOS PARA LA INDUSTRIA",
    label: "TECNÓLOGO EN DESARROLLO CREATIVO DE PRODUCTOS PARA LA INDUSTRIA",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE VIDEOJUEGOS",
    label: "TECNÓLOGO EN DESARROLLO DE VIDEOJUEGOS",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO MULTIMEDIA Y WEB",
    label: "TECNÓLOGO EN DESARROLLO MULTIMEDIA Y WEB",
  },
  {
    value: "TÉCNICO EN PROGRAMACION DE VIDEOJUEGOS",
    label: "TÉCNICO EN PROGRAMACION DE VIDEOJUEGOS",
  },
  {
    value: "TECNÓLOGO EN QUÍMICA APLICADA A LA INDUSTRIA",
    label: "TECNÓLOGO EN QUÍMICA APLICADA A LA INDUSTRIA",
  },
  {
    value: "TÉCNICO EN METEOROLOGIA AERONAUTICA",
    label: "TÉCNICO EN METEOROLOGIA AERONAUTICA",
  },
  {
    value: "TECNÓLOGO EN ASEGURAMIENTO METROLOGICO INDUSTRIAL .",
    label: "TECNÓLOGO EN ASEGURAMIENTO METROLOGICO INDUSTRIAL .",
  },
  {
    value: "TECNÓLOGO EN CONTROL DE BIOPROCESOS INDUSTRIALES",
    label: "TECNÓLOGO EN CONTROL DE BIOPROCESOS INDUSTRIALES",
  },
  {
    value: "TECNÓLOGO EN PROCESOS BIOTECNOLÓGICOS APLICADOS A LA INDUSTRIA",
    label: "TECNÓLOGO EN PROCESOS BIOTECNOLÓGICOS APLICADOS A LA INDUSTRIA",
  },
  {
    value: "TÉCNICO EN ALISTAMIENTO DE LABORATORIOS DE MICROBIOLOGIA Y BIOTECNOLOGIA",
    label: "TÉCNICO EN ALISTAMIENTO DE LABORATORIOS DE MICROBIOLOGIA Y BIOTECNOLOGIA",
  },
  {
    value: "TÉCNICO EN PROPAGACION MASIVA DE MATERIAL VEGETAL",
    label: "TÉCNICO EN PROPAGACION MASIVA DE MATERIAL VEGETAL",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE RECURSOS NATURALES",
    label: "TECNÓLOGO EN GESTIÓN DE RECURSOS NATURALES",
  },
  {
    value: "TÉCNICO EN CONSERVACION DE LA BIODIVERSIDAD Y LOS ECOSISTEMAS",
    label: "TÉCNICO EN CONSERVACION DE LA BIODIVERSIDAD Y LOS ECOSISTEMAS",
  },
  {
    value: "TÉCNICO EN CONSERVACION DE RECURSOS NATURALES",
    label: "TÉCNICO EN CONSERVACION DE RECURSOS NATURALES",
  },
  {
    value: "TÉCNICO EN APROVECHAMIENTO SUSTENTABLE DE LA BIODIVERSIDAD VEGETAL",
    label: "TÉCNICO EN APROVECHAMIENTO SUSTENTABLE DE LA BIODIVERSIDAD VEGETAL",
  },
  {
    value: "TÉCNICO EN MONITOREO AMBIENTAL",
    label: "TÉCNICO EN MONITOREO AMBIENTAL",
  },
  {
    value: "TECNÓLOGO EN SALUD AMBIENTAL Y SEGURIDAD SANITARIA",
    label: "TECNÓLOGO EN SALUD AMBIENTAL Y SEGURIDAD SANITARIA",
  },
  {
    value: "TECNÓLOGO EN PREVENCION Y CONTROL AMBIENTAL",
    label: "TECNÓLOGO EN PREVENCION Y CONTROL AMBIENTAL",
  },
  {
    value: "TÉCNICO EN PROMOTORIA EN MANEJO AMBIENTAL",
    label: "TÉCNICO EN PROMOTORIA EN MANEJO AMBIENTAL",
  },
  {
    value: "TÉCNICO EN GESTION COMUNITARIA DEL RIESGO DE DESASTRES",
    label: "TÉCNICO EN GESTION COMUNITARIA DEL RIESGO DE DESASTRES",
  },
  {
    value: "TECNÓLOGO EN CONSTRUCCION EN EDIFICACIONES.",
    label: "TECNÓLOGO EN CONSTRUCCION EN EDIFICACIONES.",
  },
  {
    value: "TECNÓLOGO EN CONSTRUCCION DE INFRAESTRUCTURA VIAL",
    label: "TECNÓLOGO EN CONSTRUCCION DE INFRAESTRUCTURA VIAL",
  },
  {
    value: "TÉCNICO EN ELABORACION DE ENSAYOS DE SUELOS Y CONCRETOS",
    label: "TÉCNICO EN ELABORACION DE ENSAYOS DE SUELOS Y CONCRETOS",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE OBRAS DE INFRAESTRUCTURA VIAL",
    label: "TECNÓLOGO EN SUPERVISION DE OBRAS DE INFRAESTRUCTURA VIAL",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO MECANICO INDUSTRIAL.",
    label: "TECNÓLOGO EN MANTENIMIENTO MECANICO INDUSTRIAL.",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE COMPONENTES MECANICOS",
    label: "TECNÓLOGO EN DESARROLLO DE COMPONENTES MECANICOS",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .",
    label: "TECNÓLOGO EN MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .",
  },
  {
    value: "TECNÓLOGO EN DISEÑO E INTEGRACIÓN DE AUTOMATISMOS MECATRÓNICOS",
    label: "TECNÓLOGO EN DISEÑO E INTEGRACIÓN DE AUTOMATISMOS MECATRÓNICOS",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO MECATRÓNICO DE AUTOMOTORES",
    label: "TECNÓLOGO EN MANTENIMIENTO MECATRÓNICO DE AUTOMOTORES",
  },
  {
    value: "TECNÓLOGO EN TEXTIL",
    label: "TECNÓLOGO EN TEXTIL",
  },
  {
    value: "TECNÓLOGO EN AUTOMATIZACIÓN INDUSTRIAL",
    label: "TECNÓLOGO EN AUTOMATIZACIÓN INDUSTRIAL",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE LA PRODUCCIÓN INDUSTRIAL",
    label: "TECNÓLOGO EN GESTIÓN DE LA PRODUCCIÓN INDUSTRIAL",
  },
  {
    value: "TÉCNICO EN PROCESOS DE MANUFACTURA.",
    label: "TÉCNICO EN PROCESOS DE MANUFACTURA.",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE SISTEMAS ELECTRONICOS INDUSTRIALES",
    label: "TECNÓLOGO EN DESARROLLO DE SISTEMAS ELECTRONICOS INDUSTRIALES",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE PRODUCTOS ELECTRONICOS",
    label: "TECNÓLOGO EN DESARROLLO DE PRODUCTOS ELECTRONICOS",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO DE EQUIPO BIOMÉDICO",
    label: "TECNÓLOGO EN MANTENIMIENTO DE EQUIPO BIOMÉDICO",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO ELECTRÓNICO E INSTRUMENTAL INDUSTRIAL",
    label: "TECNÓLOGO EN MANTENIMIENTO ELECTRÓNICO E INSTRUMENTAL INDUSTRIAL",
  },
  {
    value: "TECNÓLOGO EN AUTOMATIZACION DE SISTEMAS MECATRONICOS",
    label: "TECNÓLOGO EN AUTOMATIZACION DE SISTEMAS MECATRONICOS",
  },
  {
    value:
      "TECNÓLOGO EN IMPLEMENTACION Y MANTENIMIENTO DE SISTEMAS DE INSTRUMENTACION Y CONTROL DE PROCESOS INDUSTRIALES",
    label:
      "TECNÓLOGO EN IMPLEMENTACION Y MANTENIMIENTO DE SISTEMAS DE INSTRUMENTACION Y CONTROL DE PROCESOS INDUSTRIALES",
  },
  {
    value: "TÉCNICO EN INSTRUMENTACION INDUSTRIAL.",
    label: "TÉCNICO EN INSTRUMENTACION INDUSTRIAL.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..",
    label: "TÉCNICO EN MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..",
  },
  {
    value:
      "TECNÓLOGO EN MANTENIMIENTO DE SISTEMAS ELÉCTRICOS ELECTRÓNICOS E INSTRUMENTOS DE AERONAVES",
    label:
      "TECNÓLOGO EN MANTENIMIENTO DE SISTEMAS ELÉCTRICOS ELECTRÓNICOS E INSTRUMENTOS DE AERONAVES",
  },
  {
    value: "TÉCNICO EN IMPLEMENTACION Y MANTENIMIENTO DE SISTEMAS DE INTERNET DE LAS COSAS",
    label: "TÉCNICO EN IMPLEMENTACION Y MANTENIMIENTO DE SISTEMAS DE INTERNET DE LAS COSAS",
  },
  {
    value: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES INALAMBRICAS",
    label: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES INALAMBRICAS",
  },
  {
    value: "TECNÓLOGO EN DISEÑO DE MOLDES PARA TRANSFORMACIÓN DE MATERIALES PLÁSTICOS",
    label: "TECNÓLOGO EN DISEÑO DE MOLDES PARA TRANSFORMACIÓN DE MATERIALES PLÁSTICOS",
  },
  {
    value: "TÉCNICO EN DIBUJO ARQUITECTÓNICO",
    label: "TÉCNICO EN DIBUJO ARQUITECTÓNICO",
  },
  {
    value: "TECNÓLOGO EN DIBUJO Y MODELADO ARQUITECTONICO Y DE INGENIERIA",
    label: "TECNÓLOGO EN DIBUJO Y MODELADO ARQUITECTONICO Y DE INGENIERIA",
  },
  {
    value: "TÉCNICO EN DIBUJO MECANICO",
    label: "TÉCNICO EN DIBUJO MECANICO",
  },
  {
    value: "TÉCNICO EN MODELADO 3D PARA LA INDUSTRIA",
    label: "TÉCNICO EN MODELADO 3D PARA LA INDUSTRIA",
  },
  {
    value: "TÉCNICO EN MODELADO DIGITAL DE PRODUCTOS INDUSTRIALES",
    label: "TÉCNICO EN MODELADO DIGITAL DE PRODUCTOS INDUSTRIALES",
  },
  {
    value: "TÉCNICO EN DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA",
    label: "TÉCNICO EN DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA",
  },
  {
    value: "TECNÓLOGO EN LEVANTAMIENTOS TOPOGRAFICOS Y GEORREFERENCIACION",
    label: "TECNÓLOGO EN LEVANTAMIENTOS TOPOGRAFICOS Y GEORREFERENCIACION",
  },
  {
    value: "TÉCNICO EN CATASTRO",
    label: "TÉCNICO EN CATASTRO",
  },
  {
    value: "TÉCNICO EN SOPORTE DE TOPOGRAFIA Y GEORREFERENCIACION",
    label: "TÉCNICO EN SOPORTE DE TOPOGRAFIA Y GEORREFERENCIACION",
  },
  {
    value: "TÉCNICO EN CATASTRO MULTIPROPOSITO",
    label: "TÉCNICO EN CATASTRO MULTIPROPOSITO",
  },
  {
    value: "TECNÓLOGO EN ANÁLISIS DE MATERIALES PARA LA INDUSTRIA",
    label: "TECNÓLOGO EN ANÁLISIS DE MATERIALES PARA LA INDUSTRIA",
  },
  {
    value: "TÉCNICO EN INSPECCION DE MATERIALES CON PRUEBAS NO DESTRUCTIVAS",
    label: "TÉCNICO EN INSPECCION DE MATERIALES CON PRUEBAS NO DESTRUCTIVAS",
  },
  {
    value: "TECNÓLOGO EN GESTION DE LA SEGURIDAD Y SALUD EN EL TRABAJO",
    label: "TECNÓLOGO EN GESTION DE LA SEGURIDAD Y SALUD EN EL TRABAJO",
  },
  {
    value: "TECNÓLOGO EN COORDINACION EN SISTEMAS INTEGRADOS DE GESTION",
    label: "TECNÓLOGO EN COORDINACION EN SISTEMAS INTEGRADOS DE GESTION",
  },
  {
    value:
      "TECNÓLOGO EN OFICIAL ENCARGADO DE LA GUARDIA DE NAVEGACION. REGLA II/3.3 STCW/78 ENMENDADO. NIVEL OPERACIONAL.",
    label:
      "TECNÓLOGO EN OFICIAL ENCARGADO DE LA GUARDIA DE NAVEGACION. REGLA II/3.3 STCW/78 ENMENDADO. NIVEL OPERACIONAL.",
  },
  {
    value:
      "TECNÓLOGO EN OFICIAL ENCARGADO DE LA GUARDIA EN UNA CAMARA DE MAQUINAS. REGLA III/1- STCW/78 ENMENDADO. A NIVEL OPERACIONAL.",
    label:
      "TECNÓLOGO EN OFICIAL ENCARGADO DE LA GUARDIA EN UNA CAMARA DE MAQUINAS. REGLA III/1- STCW/78 ENMENDADO. A NIVEL OPERACIONAL.",
  },
  {
    value: "TECNÓLOGO EN PRODUCCION DE MULTIMEDIA",
    label: "TECNÓLOGO EN PRODUCCION DE MULTIMEDIA",
  },
  {
    value: "TECNÓLOGO EN ANALISIS Y DESARROLLO DE SISTEMAS DE INFORMACION",
    label: "TECNÓLOGO EN ANALISIS Y DESARROLLO DE SISTEMAS DE INFORMACION",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE VIDEOJUEGOS Y ENTORNOS INTERACTIVOS",
    label: "TECNÓLOGO EN DESARROLLO DE VIDEOJUEGOS Y ENTORNOS INTERACTIVOS",
  },
  {
    value:
      "TECNÓLOGO EN IMPLEMENTACION DE INFRAESTRUCTURA DE TECNOLOGIAS DE LA INFORMACION Y LAS COMUNICACIONES.",
    label:
      "TECNÓLOGO EN IMPLEMENTACION DE INFRAESTRUCTURA DE TECNOLOGIAS DE LA INFORMACION Y LAS COMUNICACIONES.",
  },
  {
    value: "TÉCNICO EN PROGRAMACION PARA ANALITICA DE DATOS.",
    label: "TÉCNICO EN PROGRAMACION PARA ANALITICA DE DATOS.",
  },
  {
    value: "TECNÓLOGO EN ANALISIS Y DESARROLLO DE SOFTWARE.",
    label: "TECNÓLOGO EN ANALISIS Y DESARROLLO DE SOFTWARE.",
  },
  {
    value: "TÉCNICO EN PROGRAMACION DE APLICACIONES Y SERVICIOS PARA LA NUBE",
    label: "TÉCNICO EN PROGRAMACION DE APLICACIONES Y SERVICIOS PARA LA NUBE",
  },
  {
    value: "TÉCNICO EN PROGRAMACION DE APLICACIONES PARA DISPOSITIVOS MOVILES",
    label: "TÉCNICO EN PROGRAMACION DE APLICACIONES PARA DISPOSITIVOS MOVILES",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE PRUEBAS DE SOFTWARE",
    label: "TÉCNICO EN PROCESAMIENTO DE PRUEBAS DE SOFTWARE",
  },
  {
    value: "TÉCNICO EN SEGURIDAD DE APLICACIONES WEB",
    label: "TÉCNICO EN SEGURIDAD DE APLICACIONES WEB",
  },
  {
    value: "TECNÓLOGO EN GESTION DE REDES DE DATOS",
    label: "TECNÓLOGO EN GESTION DE REDES DE DATOS",
  },
  {
    value: "TÉCNICO EN SANEAMIENTO Y SALUD AMBIENTAL",
    label: "TÉCNICO EN SANEAMIENTO Y SALUD AMBIENTAL",
  },
  {
    value: "TÉCNICO EN ALISTAMIENTO DE LABORATORIOS DE ANALISIS Y ENSAYOS PARA LA INDUSTRIA",
    label: "TÉCNICO EN ALISTAMIENTO DE LABORATORIOS DE ANALISIS Y ENSAYOS PARA LA INDUSTRIA",
  },
  {
    value: "TÉCNICO EN ANALISIS QUIMICO DE CARBONES Y MINERALES",
    label: "TÉCNICO EN ANALISIS QUIMICO DE CARBONES Y MINERALES",
  },
  {
    value: "TÉCNICO EN MEDICIONES FISICAS",
    label: "TÉCNICO EN MEDICIONES FISICAS",
  },
  {
    value: "TÉCNICO EN APLICACION DE PROCEDIMIENTOS DE LABORATORIO QUIMICO",
    label: "TÉCNICO EN APLICACION DE PROCEDIMIENTOS DE LABORATORIO QUIMICO",
  },
  {
    value: "TÉCNICO EN ANALISIS QUIMICO DE CARBONES Y MINERALES.",
    label: "TÉCNICO EN ANALISIS QUIMICO DE CARBONES Y MINERALES.",
  },
  {
    value: "TÉCNICO EN AGROTRONICA",
    label: "TÉCNICO EN AGROTRONICA",
  },
  {
    value: "TÉCNICO EN INSTALACION DE REDES DE COMPUTADORES .",
    label: "TÉCNICO EN INSTALACION DE REDES DE COMPUTADORES .",
  },
  {
    value: "TÉCNICO EN CONTROL DE LA SEGURIDAD DIGITAL.",
    label: "TÉCNICO EN CONTROL DE LA SEGURIDAD DIGITAL.",
  },
  {
    value: "TÉCNICO EN PROGRAMACION DE SOFTWARE .",
    label: "TÉCNICO EN PROGRAMACION DE SOFTWARE .",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE EQUIPOS DE COMPUTO.",
    label: "TÉCNICO EN MANTENIMIENTO DE EQUIPOS DE COMPUTO.",
  },
  {
    value: "TÉCNICO EN SISTEMAS TELEINFORMÁTICOS",
    label: "TÉCNICO EN SISTEMAS TELEINFORMÁTICOS",
  },
  {
    value:
      "TÉCNICO EN TRATAMIENTO DE RIESGOS DE CIBERSEGURIDAD EN LA MICRO, PEQUEÑA Y MEDIANA EMPRESA (MIPYMES).",
    label:
      "TÉCNICO EN TRATAMIENTO DE RIESGOS DE CIBERSEGURIDAD EN LA MICRO, PEQUEÑA Y MEDIANA EMPRESA (MIPYMES).",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE DATOS PARA MODELOS DE INTELIGENCIA ARTIFICIAL.",
    label: "TÉCNICO EN PROCESAMIENTO DE DATOS PARA MODELOS DE INTELIGENCIA ARTIFICIAL.",
  },
  {
    value: "TECNÓLOGO EN RADIOLOGIA E IMAGENES DIAGNOSTICAS.",
    label: "TECNÓLOGO EN RADIOLOGIA E IMAGENES DIAGNOSTICAS.",
  },
  {
    value: "TÉCNICO EN SALUD ORAL",
    label: "TÉCNICO EN SALUD ORAL",
  },
  {
    value: "TECNÓLOGO EN ATENCION PREHOSPITALARIA.",
    label: "TECNÓLOGO EN ATENCION PREHOSPITALARIA.",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO Y ADAPTACION DE PROTESIS Y ORTESIS.",
    label: "TECNÓLOGO EN DESARROLLO Y ADAPTACION DE PROTESIS Y ORTESIS.",
  },
  {
    value: "TÉCNICO EN ENFERMERIA.",
    label: "TÉCNICO EN ENFERMERIA.",
  },
  {
    value: "TÉCNICO EN SALUD PUBLICA",
    label: "TÉCNICO EN SALUD PUBLICA",
  },
  {
    value: "TECNÓLOGO EN GESTION DE LA SALUD AMBIENTAL Y SEGURIDAD SANITARIA",
    label: "TECNÓLOGO EN GESTION DE LA SALUD AMBIENTAL Y SEGURIDAD SANITARIA",
  },
  {
    value: "TECNÓLOGO EN REGENCIA DE FARMACIA",
    label: "TECNÓLOGO EN REGENCIA DE FARMACIA",
  },
  {
    value: "TÉCNICO EN SERVICIOS FARMACEUTICOS",
    label: "TÉCNICO EN SERVICIOS FARMACEUTICOS",
  },
  {
    value: "TÉCNICO EN MECANICA DENTAL.",
    label: "TÉCNICO EN MECANICA DENTAL.",
  },
  {
    value: "TÉCNICO EN PROMOTORIA SOCIOAMBIENTAL EN GRUPOS ETNICOS",
    label: "TÉCNICO EN PROMOTORIA SOCIOAMBIENTAL EN GRUPOS ETNICOS",
  },
  {
    value:
      "TECNÓLOGO EN INTERPRETACION Y TRADUCCION EN LENGUA DE SEÑAS COLOMBIANA (LSC) - ESPAÑOL",
    label:
      "TECNÓLOGO EN INTERPRETACION Y TRADUCCION EN LENGUA DE SEÑAS COLOMBIANA (LSC) - ESPAÑOL",
  },
  {
    value: "TECNÓLOGO EN PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES",
    label: "TECNÓLOGO EN PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES",
  },
  {
    value: "TÉCNICO EN EJECUCION DEL TROMBON",
    label: "TÉCNICO EN EJECUCION DEL TROMBON",
  },
  {
    value: "TECNÓLOGO EN COORDINACIÓN DE ESCUELAS DE MÚSICA",
    label: "TECNÓLOGO EN COORDINACIÓN DE ESCUELAS DE MÚSICA",
  },
  {
    value: "TECNÓLOGO EN PRODUCCION DANCISTICA",
    label: "TECNÓLOGO EN PRODUCCION DANCISTICA",
  },
  {
    value: "TECNÓLOGO EN ANIMACION DIGITAL",
    label: "TECNÓLOGO EN ANIMACION DIGITAL",
  },
  {
    value: "TECNÓLOGO EN GESTION BIBLIOTECARIA .",
    label: "TECNÓLOGO EN GESTION BIBLIOTECARIA .",
  },
  {
    value: "TECNÓLOGO EN FOTOGRAFIA Y PROCESOS DIGITALES",
    label: "TECNÓLOGO EN FOTOGRAFIA Y PROCESOS DIGITALES",
  },
  {
    value:
      "TECNÓLOGO EN PRODUCCION DE IMAGENES CON CAMARAS DE CINE Y TELEVISION DIGITAL",
    label:
      "TECNÓLOGO EN PRODUCCION DE IMAGENES CON CAMARAS DE CINE Y TELEVISION DIGITAL",
  },
  {
    value: "TÉCNICO EN ELABORACION DE AUDIOVISUALES.",
    label: "TÉCNICO EN ELABORACION DE AUDIOVISUALES.",
  },
  {
    value: "TÉCNICO EN OPERACION DE CAMARA PARA CINE Y TELEVISION DIGITAL.",
    label: "TÉCNICO EN OPERACION DE CAMARA PARA CINE Y TELEVISION DIGITAL.",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE MEDIOS GRAFICOS VISUALES",
    label: "TECNÓLOGO EN DESARROLLO DE MEDIOS GRAFICOS VISUALES",
  },
  {
    value: "TECNÓLOGO EN PRODUCCION DE SONIDO PARA MEDIOS AUDIOVISUALES.",
    label: "TECNÓLOGO EN PRODUCCION DE SONIDO PARA MEDIOS AUDIOVISUALES.",
  },
  {
    value: "TÉCNICO EN DESARROLLO DE EFECTOS VISUALES.",
    label: "TÉCNICO EN DESARROLLO DE EFECTOS VISUALES.",
  },
  {
    value: "TÉCNICO EN ASISTENTE DE DIRECCIÓN Y SUPERVISIÓN DE SCRIPT",
    label: "TÉCNICO EN ASISTENTE DE DIRECCIÓN Y SUPERVISIÓN DE SCRIPT",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION Y MONTAJE DE ESCENOGRAFIAS",
    label: "TÉCNICO EN CONSTRUCCION Y MONTAJE DE ESCENOGRAFIAS",
  },
  {
    value: "TÉCNICO EN EXPRESION PARA LAS ARTES ESCENICAS.",
    label: "TÉCNICO EN EXPRESION PARA LAS ARTES ESCENICAS.",
  },
  {
    value: "TÉCNICO EN ILUMINACION",
    label: "TÉCNICO EN ILUMINACION",
  },
  {
    value: "TÉCNICO EN EJECUCION DE ARTES CIRCENSES",
    label: "TÉCNICO EN EJECUCION DE ARTES CIRCENSES",
  },
  {
    value: "TECNÓLOGO EN ANIMACION 3D",
    label: "TECNÓLOGO EN ANIMACION 3D",
  },
  {
    value: "TECNÓLOGO EN COMUNICACIÓN COMERCIAL",
    label: "TECNÓLOGO EN COMUNICACIÓN COMERCIAL",
  },
  {
    value: "TECNÓLOGO EN DECORACIÓN DE ESPACIOS INTERIORES",
    label: "TECNÓLOGO EN DECORACIÓN DE ESPACIOS INTERIORES",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.",
    label: "TECNÓLOGO EN DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.",
  },
  {
    value: "TECNÓLOGO EN DISEÑO DE COMPONENTES PARA CALZADO",
    label: "TECNÓLOGO EN DISEÑO DE COMPONENTES PARA CALZADO",
  },
  {
    value: "TÉCNICO EN ELABORACION DE VIOLIN Y VIOLA",
    label: "TÉCNICO EN ELABORACION DE VIOLIN Y VIOLA",
  },
  {
    value: "TÉCNICO EN PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR",
    label: "TÉCNICO EN PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR",
  },
  {
    value: "TECNÓLOGO EN DESARROLLO DE COLECCIONES DE CALZADO Y MARROQUINERIA.",
    label: "TECNÓLOGO EN DESARROLLO DE COLECCIONES DE CALZADO Y MARROQUINERIA.",
  },
  {
    value: "TÉCNICO EN PATRONAJE INDUSTRIAL DE MARROQUINERIA",
    label: "TÉCNICO EN PATRONAJE INDUSTRIAL DE MARROQUINERIA",
  },
  {
    value: "TÉCNICO EN PATRONAJE INDUSTRIAL DE CALZADO",
    label: "TÉCNICO EN PATRONAJE INDUSTRIAL DE CALZADO",
  },
  {
    value: "TÉCNICO EN INTERVENCION GRAFICA URBANA",
    label: "TÉCNICO EN INTERVENCION GRAFICA URBANA",
  },
  {
    value: "TÉCNICO EN MODELADO 3D PARA JOYERIA.",
    label: "TÉCNICO EN MODELADO 3D PARA JOYERIA.",
  },
  {
    value: "TECNÓLOGO EN ANIMACION 3D.",
    label: "TECNÓLOGO EN ANIMACION 3D.",
  },
  {
    value: "TÉCNICO EN INTEGRACION DE CONTENIDOS DIGITALES.",
    label: "TÉCNICO EN INTEGRACION DE CONTENIDOS DIGITALES.",
  },
  {
    value: "TECNÓLOGO EN ENTRENAMIENTO DEPORTIVO",
    label: "TECNÓLOGO EN ENTRENAMIENTO DEPORTIVO",
  },
  {
    value: "TÉCNICO EN EJECUCION DE CLASES GRUPALES ORIENTADAS AL FITNESS",
    label: "TÉCNICO EN EJECUCION DE CLASES GRUPALES ORIENTADAS AL FITNESS",
  },
  {
    value: "TECNÓLOGO EN ACTIVIDAD FISICA",
    label: "TECNÓLOGO EN ACTIVIDAD FISICA",
  },
  {
    value: "TÉCNICO EN EJECUCION DE CLASES GRUPALES ORIENTADAS AL FITNESS.",
    label: "TÉCNICO EN EJECUCION DE CLASES GRUPALES ORIENTADAS AL FITNESS.",
  },
  {
    value: "TÉCNICO EN JUZGAMIENTO Y REGLAMENTACION DEPORTIVA",
    label: "TÉCNICO EN JUZGAMIENTO Y REGLAMENTACION DEPORTIVA",
  },
  {
    value: "TÉCNICO EN ELABORACION ARTESANAL DE INSTRUMENTOS MUSICALES",
    label: "TÉCNICO EN ELABORACION ARTESANAL DE INSTRUMENTOS MUSICALES",
  },
  {
    value: "TÉCNICO EN REPARACION Y MANTENIMIENTO DE INSTRUMENTOS MUSICALES",
    label: "TÉCNICO EN REPARACION Y MANTENIMIENTO DE INSTRUMENTOS MUSICALES",
  },
  {
    value: "TÉCNICO EN ELABORACION DE OBJETOS ARTESANALES CON SEMILLAS Y MADERABLES",
    label: "TÉCNICO EN ELABORACION DE OBJETOS ARTESANALES CON SEMILLAS Y MADERABLES",
  },
  {
    value: "TÉCNICO EN PRODUCCION AUDIO DIGITAL.",
    label: "TÉCNICO EN PRODUCCION AUDIO DIGITAL.",
  },
  {
    value: "TÉCNICO EN INTERPRETACION DE INSTRUMENTOS MUSICALES.",
    label: "TÉCNICO EN INTERPRETACION DE INSTRUMENTOS MUSICALES.",
  },
  {
    value: "TÉCNICO EN EJECUCION DE LA DANZA.",
    label: "TÉCNICO EN EJECUCION DE LA DANZA.",
  },
  {
    value: "TECNÓLOGO EN GESTION COMERCIAL DE NEGOCIOS VERDES",
    label: "TECNÓLOGO EN GESTION COMERCIAL DE NEGOCIOS VERDES",
  },
  {
    value: "TECNÓLOGO EN DIRECCIÓN DE VENTAS",
    label: "TECNÓLOGO EN DIRECCIÓN DE VENTAS",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE MERCADOS",
    label: "TECNÓLOGO EN GESTIÓN DE MERCADOS",
  },
  {
    value: "TECNÓLOGO EN BIOCOMERCIO SOSTENIBLE",
    label: "TECNÓLOGO EN BIOCOMERCIO SOSTENIBLE",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE VENTAS",
    label: "TECNÓLOGO EN SUPERVISION DE VENTAS",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN EMPRESARIAL",
    label: "TECNÓLOGO EN GESTIÓN EMPRESARIAL",
  },
  {
    value: "TECNÓLOGO EN COORDINACION DE SERVICIOS HOTELEROS",
    label: "TECNÓLOGO EN COORDINACION DE SERVICIOS HOTELEROS",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN INTEGRAL EN FONDOS DE PENSIONES Y CESANTÍAS",
    label: "TECNÓLOGO EN GESTIÓN INTEGRAL EN FONDOS DE PENSIONES Y CESANTÍAS",
  },
  {
    value: "TÉCNICO EN GUIA INTERPRETE PARA PERSONA SORDOCIEGA.",
    label: "TÉCNICO EN GUIA INTERPRETE PARA PERSONA SORDOCIEGA.",
  },
  {
    value: "TECNÓLOGO EN GUIANZA TURISTICA.",
    label: "TECNÓLOGO EN GUIANZA TURISTICA.",
  },
  {
    value: "TÉCNICO EN ASESORIA COMERCIAL",
    label: "TÉCNICO EN ASESORIA COMERCIAL",
  },
  {
    value: "TÉCNICO EN COMERCIO DE PRODUCTOS SOSTENIBLES",
    label: "TÉCNICO EN COMERCIO DE PRODUCTOS SOSTENIBLES",
  },
  {
    value: "TÉCNICO EN COMERCIO DE PRODUCTOS MAYORISTAS",
    label: "TÉCNICO EN COMERCIO DE PRODUCTOS MAYORISTAS",
  },
  {
    value: "TÉCNICO EN COMERCIALIZACIÓN DE PRODUCTOS MASIVOS",
    label: "TÉCNICO EN COMERCIALIZACIÓN DE PRODUCTOS MASIVOS",
  },
  {
    value: "TÉCNICO EN OPERACIONES DE LOGISTICA COMERCIAL EN GRANDES SUPERFICIES",
    label: "TÉCNICO EN OPERACIONES DE LOGISTICA COMERCIAL EN GRANDES SUPERFICIES",
  },
  {
    value: "TÉCNICO EN OPERACIONES COMERCIALES",
    label: "TÉCNICO EN OPERACIONES COMERCIALES",
  },
  {
    value: "TÉCNICO EN OPERACIONES COMERCIALES",
    label: "TÉCNICO EN OPERACIONES COMERCIALES",
  },
  {
    value: "TÉCNICO EN VENTA DE PRODUCTOS EN LINEA",
    label: "TÉCNICO EN VENTA DE PRODUCTOS EN LINEA",
  },
  {
    value: "TÉCNICO EN IMPULSO MULTICANAL DE PRODUCTOS ALIMENTICIOS",
    label: "TÉCNICO EN IMPULSO MULTICANAL DE PRODUCTOS ALIMENTICIOS",
  },
  {
    value: "TÉCNICO EN MONTAJE DE EXHIBICIONES COMERCIALES",
    label: "TÉCNICO EN MONTAJE DE EXHIBICIONES COMERCIALES",
  },
  {
    value: "TÉCNICO EN PROMOCION DE CONTENIDOS EN MEDIOS DIGITALES",
    label: "TÉCNICO EN PROMOCION DE CONTENIDOS EN MEDIOS DIGITALES",
  },
  {
    value: "TÉCNICO EN COMERCIALIZACIÓN DE ALIMENTOS",
    label: "TÉCNICO EN COMERCIALIZACIÓN DE ALIMENTOS",
  },
  {
    value: "TÉCNICO EN OPERACIONES COMERCIALES EN RETAIL",
    label: "TÉCNICO EN OPERACIONES COMERCIALES EN RETAIL",
  },
  {
    value: "TÉCNICO EN OPERACIONES DE CAJA Y SERVICIOS EN ALMACENES DE CADENA",
    label: "TÉCNICO EN OPERACIONES DE CAJA Y SERVICIOS EN ALMACENES DE CADENA",
  },
  {
    value: "TÉCNICO EN OPERACION TURISTICA LOCAL",
    label: "TÉCNICO EN OPERACION TURISTICA LOCAL",
  },
  {
    value: "TÉCNICO EN SERVICIOS DE AGENCIAS DE VIAJES",
    label: "TÉCNICO EN SERVICIOS DE AGENCIAS DE VIAJES",
  },
  {
    value: "TÉCNICO EN SERVICIO AEROPORTUARIO A PASAJEROS",
    label: "TÉCNICO EN SERVICIO AEROPORTUARIO A PASAJEROS",
  },
  {
    value: "TÉCNICO EN SERVICIO DE RECEPCION HOTELERA",
    label: "TÉCNICO EN SERVICIO DE RECEPCION HOTELERA",
  },
  {
    value: "TÉCNICO EN SERVICIOS DE ALOJAMIENTO",
    label: "TÉCNICO EN SERVICIOS DE ALOJAMIENTO",
  },
  {
    value: "TÉCNICO EN OPERACION DE ALOJAMIENTOS RURALES",
    label: "TÉCNICO EN OPERACION DE ALOJAMIENTOS RURALES",
  },
  {
    value: "TÉCNICO EN RECREACION.",
    label: "TÉCNICO EN RECREACION.",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE SERVICIOS RECREATIVOS",
    label: "TECNÓLOGO EN GESTIÓN DE SERVICIOS RECREATIVOS",
  },
  {
    value: "TÉCNICO EN ANIMACION TURISTICA",
    label: "TÉCNICO EN ANIMACION TURISTICA",
  },
  {
    value: "TÉCNICO EN DESPOSTE, PORCIONADO Y EXHIBICION DE CARNES",
    label: "TÉCNICO EN DESPOSTE, PORCIONADO Y EXHIBICION DE CARNES",
  },
  {
    value: "TÉCNICO EN CORTE Y VENTA DE CARNES.",
    label: "TÉCNICO EN CORTE Y VENTA DE CARNES.",
  },
  {
    value: "TÉCNICO EN CORTE Y VENTA DE CARNES",
    label: "TÉCNICO EN CORTE Y VENTA DE CARNES",
  },
  {
    value: "TÉCNICO EN PANIFICACION.",
    label: "TÉCNICO EN PANIFICACION.",
  },
  {
    value: "TÉCNICO EN PASTELERIA",
    label: "TÉCNICO EN PASTELERIA",
  },
  {
    value: "TÉCNICO EN PANADERIA",
    label: "TÉCNICO EN PANADERIA",
  },
  {
    value: "TÉCNICO EN PANIFICACION",
    label: "TÉCNICO EN PANIFICACION",
  },
  {
    value: "TÉCNICO EN SERVICIO DE RESTAURANTE Y BAR",
    label: "TÉCNICO EN SERVICIO DE RESTAURANTE Y BAR",
  },
  {
    value: "TÉCNICO EN PRODUCCION DE ALIMENTOS PARA LINEAS INSTITUCIONALES",
    label: "TÉCNICO EN PRODUCCION DE ALIMENTOS PARA LINEAS INSTITUCIONALES",
  },
  {
    value: "TÉCNICO EN COCINA.",
    label: "TÉCNICO EN COCINA.",
  },
  {
    value: "TÉCNICO EN SERVICIOS DE BARISMO",
    label: "TÉCNICO EN SERVICIOS DE BARISMO",
  },
  {
    value: "TÉCNICO EN PROCESOS DE PRODUCCION PANELERA",
    label: "TÉCNICO EN PROCESOS DE PRODUCCION PANELERA",
  },
  {
    value: "TÉCNICO EN ATENCION EN INCENDIOS, RESCATES Y OTRAS EMERGENCIAS..",
    label: "TÉCNICO EN ATENCION EN INCENDIOS, RESCATES Y OTRAS EMERGENCIAS..",
  },
  {
    value: "TÉCNICO EN SEGURIDAD DE INSTALACIONES",
    label: "TÉCNICO EN SEGURIDAD DE INSTALACIONES",
  },
  {
    value: "TÉCNICO EN .ATENCION INTEGRAL A LA PRIMERA INFANCIA",
    label: "TÉCNICO EN .ATENCION INTEGRAL A LA PRIMERA INFANCIA",
  },
  {
    value: "TÉCNICO EN PELUQUERIA.",
    label: "TÉCNICO EN PELUQUERIA.",
  },
  {
    value: "TÉCNICO EN TANATOPRAXIA.",
    label: "TÉCNICO EN TANATOPRAXIA.",
  },
  {
    value: "TÉCNICO EN COSMETOLOGIA Y ESTETICA INTEGRAL..",
    label: "TÉCNICO EN COSMETOLOGIA Y ESTETICA INTEGRAL..",
  },
  {
    value: "TÉCNICO EN MAQUILLAJE SOCIAL, ARTISTICO Y DE CARACTERIZACION",
    label: "TÉCNICO EN MAQUILLAJE SOCIAL, ARTISTICO Y DE CARACTERIZACION",
  },
  {
    value: "TÉCNICO EN AGENTE DE TRANSITO Y TRANSPORTE",
    label: "TÉCNICO EN AGENTE DE TRANSITO Y TRANSPORTE",
  },
  {
    value: "TÉCNICO EN EJECUCION DE EVENTOS DEPORTIVOS Y RECREATIVOS",
    label: "TÉCNICO EN EJECUCION DE EVENTOS DEPORTIVOS Y RECREATIVOS",
  },
  {
    value: "TÉCNICO EN EJECUCION DE PROGRAMAS DEPORTIVOS.",
    label: "TÉCNICO EN EJECUCION DE PROGRAMAS DEPORTIVOS.",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE PROCESOS MINEROS",
    label: "TECNÓLOGO EN SUPERVISION DE PROCESOS MINEROS",
  },
  {
    value: "TECNÓLOGO EN MECANIZACION PARA LA AGRICULTURA INTELIGENTE",
    label: "TECNÓLOGO EN MECANIZACION PARA LA AGRICULTURA INTELIGENTE",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN AGRÍCOLA",
    label: "TECNÓLOGO EN PRODUCCIÓN AGRÍCOLA",
  },
  {
    value: "TÉCNICO EN SUPERVISION DE ACTIVIDADES BANANERAS",
    label: "TÉCNICO EN SUPERVISION DE ACTIVIDADES BANANERAS",
  },
  {
    value: "TECNÓLOGO EN AGRICULTURA DE PRECISION",
    label: "TECNÓLOGO EN AGRICULTURA DE PRECISION",
  },
  {
    value: "TECNÓLOGO EN AGROBIOTECNOLOGÍA",
    label: "TECNÓLOGO EN AGROBIOTECNOLOGÍA",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN AGROPECUARIA ECOLÓGICA",
    label: "TECNÓLOGO EN PRODUCCIÓN AGROPECUARIA ECOLÓGICA",
  },
  {
    value: "TECNÓLOGO EN GESTION DE LA PRODUCCION AGRICOLA",
    label: "TECNÓLOGO EN GESTION DE LA PRODUCCION AGRICOLA",
  },
  {
    value: "TECNÓLOGO EN GESTION DE EMPRESAS PECUARIAS",
    label: "TECNÓLOGO EN GESTION DE EMPRESAS PECUARIAS",
  },
  {
    value: "TECNÓLOGO EN MANEJO Y APROVECHAMIENTO FORESTAL",
    label: "TECNÓLOGO EN MANEJO Y APROVECHAMIENTO FORESTAL",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE EMPRESAS AGROPECUARIAS",
    label: "TECNÓLOGO EN GESTIÓN DE EMPRESAS AGROPECUARIAS",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN GANADERA",
    label: "TECNÓLOGO EN PRODUCCIÓN GANADERA",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN DE ESPECIES MENORES",
    label: "TECNÓLOGO EN PRODUCCIÓN DE ESPECIES MENORES",
  },
  {
    value: "TÉCNICO EN CULTIVO Y COSECHA DE LA PALMA DE ACEITE",
    label: "TÉCNICO EN CULTIVO Y COSECHA DE LA PALMA DE ACEITE",
  },
  {
    value: "TÉCNICO EN PRODUCCION DE CAFE",
    label: "TÉCNICO EN PRODUCCION DE CAFE",
  },
  {
    value: "TÉCNICO EN MANEJO EMPRESARIAL DE LA FINCA",
    label: "TÉCNICO EN MANEJO EMPRESARIAL DE LA FINCA",
  },
  {
    value: "TECNÓLOGO EN GESTION AGROEMPRESARIAL",
    label: "TECNÓLOGO EN GESTION AGROEMPRESARIAL",
  },
  {
    value: "TECNÓLOGO EN ACUICULTURA",
    label: "TECNÓLOGO EN ACUICULTURA",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE LABORES MINERAS",
    label: "TECNÓLOGO EN SUPERVISION DE LABORES MINERAS",
  },
  {
    value: "TÉCNICO EN AVANCE DE TUNELES MINEROS.",
    label: "TÉCNICO EN AVANCE DE TUNELES MINEROS.",
  },
  {
    value: "TÉCNICO EN LABORES SUBTERRANEAS.",
    label: "TÉCNICO EN LABORES SUBTERRANEAS.",
  },
  {
    value: "TÉCNICO EN PERFORACION Y VOLADURA.",
    label: "TÉCNICO EN PERFORACION Y VOLADURA.",
  },
  {
    value: "TÉCNICO EN PRODUCCION DE PETROLEO Y GAS.",
    label: "TÉCNICO EN PRODUCCION DE PETROLEO Y GAS.",
  },
  {
    value: "TÉCNICO EN PERFORACION Y COMPLETAMIENTO DE POZOS DE PETROLEO Y GAS",
    label: "TÉCNICO EN PERFORACION Y COMPLETAMIENTO DE POZOS DE PETROLEO Y GAS",
  },
  {
    value: "TÉCNICO EN OPERACION DE CAMION MINERO",
    label: "TÉCNICO EN OPERACION DE CAMION MINERO",
  },
  {
    value: "TÉCNICO EN TECNICO EN MANEJO DEL ARBOLADO URBANO",
    label: "TÉCNICO EN TECNICO EN MANEJO DEL ARBOLADO URBANO",
  },
  {
    value: "TÉCNICO EN TECNICO EN OPERACIONES FORESTALES.",
    label: "TÉCNICO EN TECNICO EN OPERACIONES FORESTALES.",
  },
  {
    value: "TÉCNICO EN MANEJO DE LA PRODUCCION AGROECOLOGICA",
    label: "TÉCNICO EN MANEJO DE LA PRODUCCION AGROECOLOGICA",
  },
  {
    value: "TÉCNICO EN APROVECHAMIENTO Y BENEFICIO DEL CULTIVO DEL CAUCHO NATURAL",
    label: "TÉCNICO EN APROVECHAMIENTO Y BENEFICIO DEL CULTIVO DEL CAUCHO NATURAL",
  },
  {
    value: "TÉCNICO EN PRODUCCIÓN DE CAFÉS ESPECIALES",
    label: "TÉCNICO EN PRODUCCIÓN DE CAFÉS ESPECIALES",
  },
  {
    value: "TÉCNICO EN CULTIVOS AGRICOLAS",
    label: "TÉCNICO EN CULTIVOS AGRICOLAS",
  },
  {
    value: "TÉCNICO EN PRODUCCION Y COSECHA DE CULTIVO DE CACAO",
    label: "TÉCNICO EN PRODUCCION Y COSECHA DE CULTIVO DE CACAO",
  },
  {
    value: "TÉCNICO EN ASEGURAMIENTO DE LA CALIDAD DEL CAFE EN LA FINCA",
    label: "TÉCNICO EN ASEGURAMIENTO DE LA CALIDAD DEL CAFE EN LA FINCA",
  },
  {
    value: "TÉCNICO EN SISTEMAS AGROPECUARIOS ECOLOGICOS.",
    label: "TÉCNICO EN SISTEMAS AGROPECUARIOS ECOLOGICOS.",
  },
  {
    value: "TÉCNICO EN RIEGO Y ADECUACION DE TIERRAS",
    label: "TÉCNICO EN RIEGO Y ADECUACION DE TIERRAS",
  },
  {
    value: "TÉCNICO EN PRODUCCION OVINO-CAPRINO",
    label: "TÉCNICO EN PRODUCCION OVINO-CAPRINO",
  },
  {
    value: "TÉCNICO EN PRODUCCIÓN DE CAPRINOS Y OVINOS",
    label: "TÉCNICO EN PRODUCCIÓN DE CAPRINOS Y OVINOS",
  },
  {
    value: "TÉCNICO EN PRODUCCION PECUARIA.",
    label: "TÉCNICO EN PRODUCCION PECUARIA.",
  },
  {
    value: "TÉCNICO EN PRODUCCION PORCINA.",
    label: "TÉCNICO EN PRODUCCION PORCINA.",
  },
  {
    value: "TÉCNICO EN PRODUCCION EQUINA.",
    label: "TÉCNICO EN PRODUCCION EQUINA.",
  },
  {
    value: "TÉCNICO EN PRODUCCION ACUICOLA.",
    label: "TÉCNICO EN PRODUCCION ACUICOLA.",
  },
  {
    value: "TÉCNICO EN PRODUCCION DE CULTIVOS EN AMBIENTES PROTEGIDOS",
    label: "TÉCNICO EN PRODUCCION DE CULTIVOS EN AMBIENTES PROTEGIDOS",
  },
  {
    value: "TÉCNICO EN MANEJO DE VIVEROS",
    label: "TÉCNICO EN MANEJO DE VIVEROS",
  },
  {
    value: "TÉCNICO EN FLORICULTURA",
    label: "TÉCNICO EN FLORICULTURA",
  },
  {
    value: "TÉCNICO EN RIEGO Y DRENAJE EN CULTIVOS AGRICOLAS.",
    label: "TÉCNICO EN RIEGO Y DRENAJE EN CULTIVOS AGRICOLAS.",
  },
  {
    value: "TÉCNICO EN PROYECTOS AGROPECUARIOS.",
    label: "TÉCNICO EN PROYECTOS AGROPECUARIOS.",
  },
  {
    value: "TÉCNICO EN MAYORDOMIA DE LA EMPRESA GANADERA SOSTENIBLE",
    label: "TÉCNICO EN MAYORDOMIA DE LA EMPRESA GANADERA SOSTENIBLE",
  },
  {
    value: "TÉCNICO EN PRODUCCION AGROPECUARIA",
    label: "TÉCNICO EN PRODUCCION AGROPECUARIA",
  },
  {
    value: "TÉCNICO EN MAYORDOMIA DE EMPRESAS GANADERAS",
    label: "TÉCNICO EN MAYORDOMIA DE EMPRESAS GANADERAS",
  },
  {
    value: "TÉCNICO EN PRODUCCION ANIMAL",
    label: "TÉCNICO EN PRODUCCION ANIMAL",
  },
  {
    value: "TÉCNICO EN HERRADO Y FORJA EQUINA",
    label: "TÉCNICO EN HERRADO Y FORJA EQUINA",
  },
  {
    value: "TÉCNICO EN PRODUCCIÓN DE HUEVO E INCUBACIÓN ARTIFICIAL",
    label: "TÉCNICO EN PRODUCCIÓN DE HUEVO E INCUBACIÓN ARTIFICIAL",
  },
  {
    value: "TÉCNICO EN MANEJO DE PESQUERIAS",
    label: "TÉCNICO EN MANEJO DE PESQUERIAS",
  },
  {
    value: "TÉCNICO EN PESQUERÍAS",
    label: "TÉCNICO EN PESQUERÍAS",
  },
  {
    value: "TÉCNICO EN PRODUCCION ACUICOLA..",
    label: "TÉCNICO EN PRODUCCION ACUICOLA..",
  },
  {
    value:
      "TECNÓLOGO EN PRODUCCION DE COMPONENTES MECANICOS CON MAQUINAS DE CONTROL NUMERICO COMPUTARIZADO",
    label:
      "TECNÓLOGO EN PRODUCCION DE COMPONENTES MECANICOS CON MAQUINAS DE CONTROL NUMERICO COMPUTARIZADO",
  },
  {
    value: "TECNÓLOGO EN FABRICACIÓN DE MOLDES Y TROQUELES",
    label: "TECNÓLOGO EN FABRICACIÓN DE MOLDES Y TROQUELES",
  },
  {
    value: "TECNÓLOGO EN SUPERVISIÓN DE REDES DE DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA",
    label: "TECNÓLOGO EN SUPERVISIÓN DE REDES DE DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA",
  },
  {
    value: "TECNÓLOGO EN IMPLEMENTACION DE REDES Y SERVICIOS DE TELECOMUNICACIONES",
    label: "TECNÓLOGO EN IMPLEMENTACION DE REDES Y SERVICIOS DE TELECOMUNICACIONES",
  },
  {
    value: "TECNÓLOGO EN GESTION EFICIENTE DE LA ENERGIA",
    label: "TECNÓLOGO EN GESTION EFICIENTE DE LA ENERGIA",
  },
  {
    value: "TECNÓLOGO EN ELECTRICIDAD INDUSTRIAL",
    label: "TECNÓLOGO EN ELECTRICIDAD INDUSTRIAL",
  },
  {
    value: "TECNÓLOGO EN GESTION PARA SUMINISTRO DE GAS COMBUSTIBLE",
    label: "TECNÓLOGO EN GESTION PARA SUMINISTRO DE GAS COMBUSTIBLE",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO ELECTROMECÁNICO DE EQUIPO PESADO",
    label: "TECNÓLOGO EN MANTENIMIENTO ELECTROMECÁNICO DE EQUIPO PESADO",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO MECÁNICO INDUSTRIAL",
    label: "TECNÓLOGO EN MANTENIMIENTO MECÁNICO INDUSTRIAL",
  },
  {
    value: "TECNÓLOGO EN GESTION DEL MANTENIMIENTO DE AUTOMOTORES.",
    label: "TECNÓLOGO EN GESTION DEL MANTENIMIENTO DE AUTOMOTORES.",
  },
  {
    value: "TÉCNICO EN CONTROL DE MOVILIDAD, TRANSPORTE Y SEGURIDAD VIAL",
    label: "TÉCNICO EN CONTROL DE MOVILIDAD, TRANSPORTE Y SEGURIDAD VIAL",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN LOGÍSTICA",
    label: "TECNÓLOGO EN GESTIÓN LOGÍSTICA",
  },
  {
    value: "TÉCNICO EN OPERACION EN TORNO Y FRESADORA",
    label: "TÉCNICO EN OPERACION EN TORNO Y FRESADORA",
  },
  {
    value: "TÉCNICO EN MECANICA DE EQUIPO MINERO BAJO TIERRA",
    label: "TÉCNICO EN MECANICA DE EQUIPO MINERO BAJO TIERRA",
  },
  {
    value: "TÉCNICO EN ELECTRICISTA INDUSTRIAL",
    label: "TÉCNICO EN ELECTRICISTA INDUSTRIAL",
  },
  {
    value: "TÉCNICO EN ELECTRICIDAD DE MINAS",
    label: "TÉCNICO EN ELECTRICIDAD DE MINAS",
  },
  {
    value: "TÉCNICO EN INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES",
    label: "TÉCNICO EN INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES",
  },
  {
    value:
      "TÉCNICO EN INTEGRACION DE SISTEMAS DOMOTICOS, INTERNET DE LAS COSAS Y EFICIENCIA ENERGETICA EN LA CONSTRUCCION",
    label:
      "TÉCNICO EN INTEGRACION DE SISTEMAS DOMOTICOS, INTERNET DE LAS COSAS Y EFICIENCIA ENERGETICA EN LA CONSTRUCCION",
  },
  {
    value:
      "TÉCNICO EN ELECTRICIDAD RESIDENCIAL, COMERCIAL Y DE SISTEMAS FOTOVOLTAICOS",
    label:
      "TÉCNICO EN ELECTRICIDAD RESIDENCIAL, COMERCIAL Y DE SISTEMAS FOTOVOLTAICOS",
  },
  {
    value:
      "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES AEREAS DE DISTRIBUCION DE ENERGIA ELECTRICA EN MEDIA Y BAJA TENSION",
    label:
      "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES AEREAS DE DISTRIBUCION DE ENERGIA ELECTRICA EN MEDIA Y BAJA TENSION",
  },
  {
    value:
      "TÉCNICO EN CONSTRUCCION Y MANTENIMIENTO EN LINEAS DE TRANSMISION DE ENERGIA ELECTRICA",
    label:
      "TÉCNICO EN CONSTRUCCION Y MANTENIMIENTO EN LINEAS DE TRANSMISION DE ENERGIA ELECTRICA",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO E INSTALACION DE SISTEMAS SOLARES FOTOVOLTAICOS",
    label: "TÉCNICO EN MANTENIMIENTO E INSTALACION DE SISTEMAS SOLARES FOTOVOLTAICOS",
  },
  {
    value: "TÉCNICO EN MONTAJE Y MANTENIMIENTO DE REDES AEREAS DE DISTRIBUCION DE ENERGIA ELECTRICA",
    label: "TÉCNICO EN MONTAJE Y MANTENIMIENTO DE REDES AEREAS DE DISTRIBUCION DE ENERGIA ELECTRICA",
  },
  {
    value: "TÉCNICO EN INSTALACION DE SISTEMAS DE TELEVISION SATELITAL Y TERRESTRE",
    label: "TÉCNICO EN INSTALACION DE SISTEMAS DE TELEVISION SATELITAL Y TERRESTRE",
  },
  {
    value: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES INTERNAS DE TELECOMUNICACIONES",
    label: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE REDES INTERNAS DE TELECOMUNICACIONES",
  },
  {
    value: "TÉCNICO EN INSTALACION DE REDES DE TELECOMUNICACIONES",
    label: "TÉCNICO EN INSTALACION DE REDES DE TELECOMUNICACIONES",
  },
  {
    value: "TÉCNICO EN INSTALACION DE REDES HIBRIDAS DE FIBRA OPTICA Y COAXIAL",
    label: "TÉCNICO EN INSTALACION DE REDES HIBRIDAS DE FIBRA OPTICA Y COAXIAL",
  },
  {
    value: "TÉCNICO EN INSTALACION Y REPARACION DE RED DE FIBRA OPTICA",
    label: "TÉCNICO EN INSTALACION Y REPARACION DE RED DE FIBRA OPTICA",
  },
  {
    value: "TÉCNICO EN INSTALACION DE REDES INTERNAS DE TELECOMUNICACIONES",
    label: "TÉCNICO EN INSTALACION DE REDES INTERNAS DE TELECOMUNICACIONES",
  },
  {
    value: "TÉCNICO EN INSTALACIONES HIDRAULICAS Y SANITARIAS EN EDIFICACIONES RESIDENCIALES Y COMERCIALES.",
    label: "TÉCNICO EN INSTALACIONES HIDRAULICAS Y SANITARIAS EN EDIFICACIONES RESIDENCIALES Y COMERCIALES.",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION REDES DE ACUEDUCTO Y ALCANTARILLADO.",
    label: "TÉCNICO EN CONSTRUCCION REDES DE ACUEDUCTO Y ALCANTARILLADO.",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION DE REDES DE ACUEDUCTO Y ALCANTARILLADO",
    label: "TÉCNICO EN CONSTRUCCION DE REDES DE ACUEDUCTO Y ALCANTARILLADO",
  },
  {
    value: "TÉCNICO EN SISTEMAS CONTRA INCENDIOS A BASE DE AGUA EN EDIFICACIONES",
    label: "TÉCNICO EN SISTEMAS CONTRA INCENDIOS A BASE DE AGUA EN EDIFICACIONES",
  },
  {
    value: "TÉCNICO EN INSTALACIONES PARA SUMINISTRO DE GAS COMBUSTIBLE EN EDIFICACIONES RESIDENCIALES Y COMERCIALES.",
    label: "TÉCNICO EN INSTALACIONES PARA SUMINISTRO DE GAS COMBUSTIBLE EN EDIFICACIONES RESIDENCIALES Y COMERCIALES.",
  },
  {
    value: "TÉCNICO EN INSTALACION, MANTENIMIENTO Y CONVERSION DE GASODOMESTICOS.",
    label: "TÉCNICO EN INSTALACION, MANTENIMIENTO Y CONVERSION DE GASODOMESTICOS.",
  },
  {
    value: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE ELECTROGASODOMESTICOS",
    label: "TÉCNICO EN INSTALACION Y MANTENIMIENTO DE ELECTROGASODOMESTICOS",
  },
  {
    value: "TÉCNICO EN ELECTROGASODOMESTICOS.",
    label: "TÉCNICO EN ELECTROGASODOMESTICOS.",
  },
  {
    value: "TÉCNICO EN TRAZADO, CORTE, CONFORMADO Y ARMADO EN PRODUCTOS METALICOS",
    label: "TÉCNICO EN TRAZADO, CORTE, CONFORMADO Y ARMADO EN PRODUCTOS METALICOS",
  },
  {
    value: "TÉCNICO EN CARPINTERIA METALICA.",
    label: "TÉCNICO EN CARPINTERIA METALICA.",
  },
  {
    value: "TÉCNICO EN METALISTERIA DE PLANTAS INDUSTRIALES",
    label: "TÉCNICO EN METALISTERIA DE PLANTAS INDUSTRIALES",
  },
  {
    value: "TÉCNICO EN SOLDADURA DE PRODUCTOS METALICOS EN PLATINA",
    label: "TÉCNICO EN SOLDADURA DE PRODUCTOS METALICOS EN PLATINA",
  },
  {
    value: "TÉCNICO EN CARPINTERIA.",
    label: "TÉCNICO EN CARPINTERIA.",
  },
  {
    value: "TÉCNICO EN CONSTRUCCIONES EN MADERA,",
    label: "TÉCNICO EN CONSTRUCCIONES EN MADERA,",
  },
  {
    value: "TÉCNICO EN CONSTRUCCIÓN DE VIVIENDAS MODULARES EN MADERA",
    label: "TÉCNICO EN CONSTRUCCIÓN DE VIVIENDAS MODULARES EN MADERA",
  },
  {
    value: "TÉCNICO EN FABRICACION DIGITAL DE MOBILIARIO",
    label: "TÉCNICO EN FABRICACION DIGITAL DE MOBILIARIO",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION DE PROYECTOS DE JARDINERIA CON AMOBLAMIENTO URBANO",
    label: "TÉCNICO EN CONSTRUCCION DE PROYECTOS DE JARDINERIA CON AMOBLAMIENTO URBANO",
  },
  {
    value: "TÉCNICO EN CONSTRUCCIONES LIVIANAS INDUSTRIALIZADAS EN SECO",
    label: "TÉCNICO EN CONSTRUCCIONES LIVIANAS INDUSTRIALIZADAS EN SECO",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION, MANTENIMIENTO Y REPARACION DE ESTRUCTURAS EN GUADUA",
    label: "TÉCNICO EN CONSTRUCCION, MANTENIMIENTO Y REPARACION DE ESTRUCTURAS EN GUADUA",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO Y REPARACION DE EDIFICACIONES.",
    label: "TÉCNICO EN MANTENIMIENTO Y REPARACION DE EDIFICACIONES.",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION DE EDIFICACIONES",
    label: "TÉCNICO EN CONSTRUCCION DE EDIFICACIONES",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION DE ESTRUCTURAS EN GUADUA",
    label: "TÉCNICO EN CONSTRUCCION DE ESTRUCTURAS EN GUADUA",
  },
  {
    value: "TÉCNICO EN ENCHAPES DE PISOS Y PAREDES CON MATERIAL CERAMICO Y SIMILARES",
    label: "TÉCNICO EN ENCHAPES DE PISOS Y PAREDES CON MATERIAL CERAMICO Y SIMILARES",
  },
  {
    value: "TÉCNICO EN PINTURA ARQUITECTONICA Y ACABADOS ESPECIALES",
    label: "TÉCNICO EN PINTURA ARQUITECTONICA Y ACABADOS ESPECIALES",
  },
  {
    value: "TÉCNICO EN MECANICA DE MAQUINARIA INDUSTRIAL",
    label: "TÉCNICO EN MECANICA DE MAQUINARIA INDUSTRIAL",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE MAQUINARIA PARA INDUSTRIA DEL PLASTICO",
    label: "TÉCNICO EN MANTENIMIENTO DE MAQUINARIA PARA INDUSTRIA DEL PLASTICO",
  },
  {
    value: "TÉCNICO EN MAQUINARIA NAVAL.",
    label: "TÉCNICO EN MAQUINARIA NAVAL.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE MAQUINAS DE CONFECCION INDUSTRIAL",
    label: "TÉCNICO EN MANTENIMIENTO DE MAQUINAS DE CONFECCION INDUSTRIAL",
  },
  {
    value: "TÉCNICO EN MONTAJE Y MANTENIMIENTO ELECTROMECANICO DE INSTALACIONES MINERAS BAJO TIERRA",
    label: "TÉCNICO EN MONTAJE Y MANTENIMIENTO ELECTROMECANICO DE INSTALACIONES MINERAS BAJO TIERRA",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE EQUIPO PESADO PARA INFRAESTRUCTURA, MINERIA Y TRANSPORTE.",
    label: "TÉCNICO EN MANTENIMIENTO DE EQUIPO PESADO PARA INFRAESTRUCTURA, MINERIA Y TRANSPORTE.",
  },
  {
    value: "TÉCNICO EN REPARACION DE MAQUINARIA AGRICOLA.",
    label: "TÉCNICO EN REPARACION DE MAQUINARIA AGRICOLA.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE AVIONES",
    label: "TÉCNICO EN MANTENIMIENTO DE AVIONES",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE AERONAVES EN CELULA Y MOTOPROPULSOR",
    label: "TÉCNICO EN MANTENIMIENTO DE AERONAVES EN CELULA Y MOTOPROPULSOR",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO DE LÍNEA DE HELICÓPTEROS",
    label: "TECNÓLOGO EN MANTENIMIENTO DE LÍNEA DE HELICÓPTEROS",
  },
  {
    value: "TECNÓLOGO EN MANTENIMIENTO LÍNEA DE AVIONES",
    label: "TECNÓLOGO EN MANTENIMIENTO LÍNEA DE AVIONES",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE EQUIPOS DE AIRE ACONDICIONADO Y REFRIGERACION",
    label: "TÉCNICO EN MANTENIMIENTO DE EQUIPOS DE AIRE ACONDICIONADO Y REFRIGERACION",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE LOS MOTORES DIESEL",
    label: "TÉCNICO EN MANTENIMIENTO DE LOS MOTORES DIESEL",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE VEHICULOS LIVIANOS",
    label: "TÉCNICO EN MANTENIMIENTO DE VEHICULOS LIVIANOS",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO ELECTRICO Y CONTROL ELECTRONICO DE AUTOMOTORES",
    label: "TÉCNICO EN MANTENIMIENTO ELECTRICO Y CONTROL ELECTRONICO DE AUTOMOTORES",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE SISTEMAS DE PROPULSION ELECTRICA E HIBRIDA AUTOMOTRIZ.",
    label: "TÉCNICO EN MANTENIMIENTO DE SISTEMAS DE PROPULSION ELECTRICA E HIBRIDA AUTOMOTRIZ.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.",
    label: "TÉCNICO EN MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO ELECTROMECANICO DE MOTOCICLETAS",
    label: "TÉCNICO EN MANTENIMIENTO ELECTROMECANICO DE MOTOCICLETAS",
  },
  {
    value: "TÉCNICO EN MONTAJE Y MANTENIMIENTO ELECTROMECANICO EN INSTALACIONES MINERAS",
    label: "TÉCNICO EN MONTAJE Y MANTENIMIENTO ELECTROMECANICO EN INSTALACIONES MINERAS",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE DISPOSITIVOS MOVILES DE COMUNICACION PERSONAL.",
    label: "TÉCNICO EN MANTENIMIENTO DE DISPOSITIVOS MOVILES DE COMUNICACION PERSONAL.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.",
    label: "TÉCNICO EN MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.",
  },
  {
    value: "TÉCNICO EN MANTENIMIENTO DE MOTORES FUERA DE BORDA",
    label: "TÉCNICO EN MANTENIMIENTO DE MOTORES FUERA DE BORDA",
  },
  {
    value: "TÉCNICO EN CARPINTERIA DE ALUMINIO",
    label: "TÉCNICO EN CARPINTERIA DE ALUMINIO",
  },
  {
    value: "TÉCNICO EN MECANICA DE LA BICICLETA Y PROMOCION DE LA CULTURA VIAL",
    label: "TÉCNICO EN MECANICA DE LA BICICLETA Y PROMOCION DE LA CULTURA VIAL",
  },
  {
    value: "TÉCNICO EN TAPIZADO DE MUEBLES.",
    label: "TÉCNICO EN TAPIZADO DE MUEBLES.",
  },
  {
    value: "TÉCNICO EN ELABORACION DE PRENDAS DE VESTIR SOBRE MEDIDAS",
    label: "TÉCNICO EN ELABORACION DE PRENDAS DE VESTIR SOBRE MEDIDAS",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN DE JOYERÍA",
    label: "TECNÓLOGO EN PRODUCCIÓN DE JOYERÍA",
  },
  {
    value: "TÉCNICO EN TALLA DE GEMAS PARA JOYERIA",
    label: "TÉCNICO EN TALLA DE GEMAS PARA JOYERIA",
  },
  {
    value: "TÉCNICO EN JOYERIA ARMADA",
    label: "TÉCNICO EN JOYERIA ARMADA",
  },
  {
    value: "TÉCNICO EN FUNDICION A LA CERA PERDIDA EN JOYERIA",
    label: "TÉCNICO EN FUNDICION A LA CERA PERDIDA EN JOYERIA",
  },
  {
    value: "TÉCNICO EN ENGASTE DE GEMAS EN JOYERIA",
    label: "TÉCNICO EN ENGASTE DE GEMAS EN JOYERIA",
  },
  {
    value: "TÉCNICO EN MINERIA A CIELO ABIERTO.",
    label: "TÉCNICO EN MINERIA A CIELO ABIERTO.",
  },
  {
    value: "TÉCNICO EN OPERACION DE MAQUINARIA PESADA PARA EXCAVACION.",
    label: "TÉCNICO EN OPERACION DE MAQUINARIA PESADA PARA EXCAVACION.",
  },
  {
    value: "TÉCNICO EN OPERACIÓN DE TRACTOR DE ORUGAS EN EXPLOTACIONES MINERAS",
    label: "TÉCNICO EN OPERACIÓN DE TRACTOR DE ORUGAS EN EXPLOTACIONES MINERAS",
  },
  {
    value: "TÉCNICO EN TRANSPORTE DE MATERIAL EN CAMION MINERO",
    label: "TÉCNICO EN TRANSPORTE DE MATERIAL EN CAMION MINERO",
  },
  {
    value: "TÉCNICO EN OPERACION DE MAQUINARIA AGRICOLA",
    label: "TÉCNICO EN OPERACION DE MAQUINARIA AGRICOLA",
  },
  {
    value: "TÉCNICO EN OPERACION DE ALZADORA Y COSECHADORA DE CAÑA DE AZUCAR",
    label: "TÉCNICO EN OPERACION DE ALZADORA Y COSECHADORA DE CAÑA DE AZUCAR",
  },
  {
    value: "TECNÓLOGO EN MECANIZACIÓN AGRÍCOLA",
    label: "TECNÓLOGO EN MECANIZACIÓN AGRÍCOLA",
  },
  {
    value: "TÉCNICO EN MAQUINISTA DE LOCOMOTORAS",
    label: "TÉCNICO EN MAQUINISTA DE LOCOMOTORAS",
  },
  {
    value: "TÉCNICO EN TRANSPORTE DE CARGA EN VEHICULO ARTICULADO",
    label: "TÉCNICO EN TRANSPORTE DE CARGA EN VEHICULO ARTICULADO",
  },
  {
    value: "TÉCNICO EN OPERACION DE VEHICULO DE TRANSPORTE ESPECIALIZADO DE CARGA.",
    label: "TÉCNICO EN OPERACION DE VEHICULO DE TRANSPORTE ESPECIALIZADO DE CARGA.",
  },
  {
    value:
      "TÉCNICO EN MARINERO QUE FORMA PARTE DE LA GUARDIA DE NAVEGACION. REGLA -II/4 STCW 78- ENMENDADO. A NIVEL DE APOYO",
    label:
      "TÉCNICO EN MARINERO QUE FORMA PARTE DE LA GUARDIA DE NAVEGACION. REGLA -II/4 STCW 78- ENMENDADO. A NIVEL DE APOYO",
  },
  {
    value: "TÉCNICO EN MARINERIA DE EMBARCACION FLUVIAL",
    label: "TÉCNICO EN MARINERIA DE EMBARCACION FLUVIAL",
  },
  {
    value:
      "TÉCNICO EN MARINERO QUE FORME PARTE DE LA GUARDIA EN UNA CAMARA DE MAQUINAS. REGLA III/4 STCW/78 ENMENDADO. NIVEL APOYO.",
    label:
      "TÉCNICO EN MARINERO QUE FORME PARTE DE LA GUARDIA EN UNA CAMARA DE MAQUINAS. REGLA III/4 STCW/78 ENMENDADO. NIVEL APOYO.",
  },
  {
    value: "TÉCNICO EN OPERACIONES EN PLATAFORMAS AEROPORTUARIAS",
    label: "TÉCNICO EN OPERACIONES EN PLATAFORMAS AEROPORTUARIAS",
  },
  {
    value: "TÉCNICO EN OPERACION EN TERMINALES PORTUARIAS",
    label: "TÉCNICO EN OPERACION EN TERMINALES PORTUARIAS",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION DE VIAS.",
    label: "TÉCNICO EN CONSTRUCCION DE VIAS.",
  },
  {
    value: "TÉCNICO EN MATENIMIENTO DE VIAS TERCIARIAS",
    label: "TÉCNICO EN MATENIMIENTO DE VIAS TERCIARIAS",
  },
  {
    value: "TÉCNICO EN CONSTRUCCION, MANTENIMIENTO Y REHABILITACION DE VIAS FERREAS",
    label: "TÉCNICO EN CONSTRUCCION, MANTENIMIENTO Y REHABILITACION DE VIAS FERREAS",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION EN SISTEMAS DE AGUA Y SANEAMIENTO",
    label: "TECNÓLOGO EN SUPERVISION EN SISTEMAS DE AGUA Y SANEAMIENTO",
  },
  {
    value: "TECNÓLOGO EN GESTION DE FACILIDADES PARA PRODUCCION DE HIDROCARBUROS.",
    label: "TECNÓLOGO EN GESTION DE FACILIDADES PARA PRODUCCION DE HIDROCARBUROS.",
  },
  {
    value: "TÉCNICO EN OPERACIÓN DE SISTEMAS DE POTABILIZACIÓN DE AGUA",
    label: "TÉCNICO EN OPERACIÓN DE SISTEMAS DE POTABILIZACIÓN DE AGUA",
  },
  {
    value:
      "TÉCNICO EN OPERACIÓN Y MANTENIMIENTO DE SISTEMAS DE ABASTECIMIENTO DE AGUA PARA PEQUEÑAS COMUNIDADES",
    label:
      "TÉCNICO EN OPERACIÓN Y MANTENIMIENTO DE SISTEMAS DE ABASTECIMIENTO DE AGUA PARA PEQUEÑAS COMUNIDADES",
  },
  {
    value: "TECNÓLOGO EN PROCESOS DE LA INDUSTRIA QUÍMICA",
    label: "TECNÓLOGO EN PROCESOS DE LA INDUSTRIA QUÍMICA",
  },
  {
    value: "TECNÓLOGO EN CONTROL DE CALIDAD DE ALIMENTOS",
    label: "TECNÓLOGO EN CONTROL DE CALIDAD DE ALIMENTOS",
  },
  {
    value: "TECNÓLOGO EN PROCESAMIENTO DE ALIMENTOS",
    label: "TECNÓLOGO EN PROCESAMIENTO DE ALIMENTOS",
  },
  {
    value: "TECNÓLOGO EN FABRICACIÓN DE PRODUCTOS PLÁSTICOS POR EXTRUSIÓN",
    label: "TECNÓLOGO EN FABRICACIÓN DE PRODUCTOS PLÁSTICOS POR EXTRUSIÓN",
  },
  {
    value: "TECNÓLOGO EN FABRICACIÓN DE PRODUCTOS PLÁSTICOS POR INYECCIÓN Y SOPLADO",
    label: "TECNÓLOGO EN FABRICACIÓN DE PRODUCTOS PLÁSTICOS POR INYECCIÓN Y SOPLADO",
  },
  {
    value: "TECNÓLOGO EN PROCESOS PRODUCTIVOS DE LA MADERA",
    label: "TECNÓLOGO EN PROCESOS PRODUCTIVOS DE LA MADERA",
  },
  {
    value: "TECNÓLOGO EN CONTROL DE CALIDAD EN LA INDUSTRIA DE ALIMENTOS",
    label: "TECNÓLOGO EN CONTROL DE CALIDAD EN LA INDUSTRIA DE ALIMENTOS",
  },
  {
    value: "TECNÓLOGO EN GESTION DE PROCESOS Y PRODUCCION DE MOBILIARIO",
    label: "TECNÓLOGO EN GESTION DE PROCESOS Y PRODUCCION DE MOBILIARIO",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION EN PROCESOS DE CONFECCION",
    label: "TECNÓLOGO EN SUPERVISION EN PROCESOS DE CONFECCION",
  },
  {
    value: "TECNÓLOGO EN PRODUCCIÓN DE CALZADO Y MARROQUINERÍA",
    label: "TECNÓLOGO EN PRODUCCIÓN DE CALZADO Y MARROQUINERÍA",
  },
  {
    value: "TECNÓLOGO EN CONFECCIÓN INDUSTRIAL",
    label: "TECNÓLOGO EN CONFECCIÓN INDUSTRIAL",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE PROCESOS GRAFICOS.",
    label: "TECNÓLOGO EN SUPERVISION DE PROCESOS GRAFICOS.",
  },
  {
    value: "TECNÓLOGO EN GESTION DE PROCESOS DE PREPRENSA PARA MEDIOS IMPRESOS",
    label: "TECNÓLOGO EN GESTION DE PROCESOS DE PREPRENSA PARA MEDIOS IMPRESOS",
  },
  {
    value: "TECNÓLOGO EN SUPERVISION DE LA FABRICACION DE PRODUCTOS METALICOS SOLDADOS.",
    label: "TECNÓLOGO EN SUPERVISION DE LA FABRICACION DE PRODUCTOS METALICOS SOLDADOS.",
  },
  {
    value: "TECNÓLOGO EN DISEÑO DE ELEMENTOS MECÁNICOS PARA SU FABRICACIÓN CON MÁQUINAS HERRAMIENTAS CNC",
    label: "TECNÓLOGO EN DISEÑO DE ELEMENTOS MECÁNICOS PARA SU FABRICACIÓN CON MÁQUINAS HERRAMIENTAS CNC",
  },
  {
    value: "TECNÓLOGO EN GESTIÓN DE RECURSOS EN PLANTAS DE PRODUCCIÓN",
    label: "TECNÓLOGO EN GESTIÓN DE RECURSOS EN PLANTAS DE PRODUCCIÓN",
  },
  {
    value: "TECNÓLOGO EN OPERACIÓN DE PLANTAS PETROQUÍMICAS",
    label: "TECNÓLOGO EN OPERACIÓN DE PLANTAS PETROQUÍMICAS",
  },
  {
    value: "TÉCNICO EN - IMPRESION DIGITAL",
    label: "TÉCNICO EN - IMPRESION DIGITAL",
  },
  {
    value: "TÉCNICO EN IMPRESION OFFSET.",
    label: "TÉCNICO EN IMPRESION OFFSET.",
  },
  {
    value: "TÉCNICO EN IMPRESION FLEXOGRAFICA.",
    label: "TÉCNICO EN IMPRESION FLEXOGRAFICA.",
  },
  {
    value: "TÉCNICO EN IMPRESION SERIGRAFICA.",
    label: "TÉCNICO EN IMPRESION SERIGRAFICA.",
  },
  {
    value: "TÉCNICO EN PROCESOS DE POSTPRENSA PARA LA INDUSTRIA GRAFICA.",
    label: "TÉCNICO EN PROCESOS DE POSTPRENSA PARA LA INDUSTRIA GRAFICA.",
  },
  {
    value: "TÉCNICO EN ENCUADERNACION Y ACABADOS ESPECIALES DE PRODUCTOS GRAFICOS IMPRESOS",
    label: "TÉCNICO EN ENCUADERNACION Y ACABADOS ESPECIALES DE PRODUCTOS GRAFICOS IMPRESOS",
  },
  {
    value: "TÉCNICO EN BENEFICIO DE MINERALES",
    label: "TÉCNICO EN BENEFICIO DE MINERALES",
  },
  {
    value: "TÉCNICO EN FABRICACION DE ACERO EN SIDERURGIA SEMIINTEGRADA",
    label: "TÉCNICO EN FABRICACION DE ACERO EN SIDERURGIA SEMIINTEGRADA",
  },
  {
    value: "TÉCNICO EN FABRICACION DE PIEZAS FUNDIDAS",
    label: "TÉCNICO EN FABRICACION DE PIEZAS FUNDIDAS",
  },
  {
    value: "TÉCNICO EN CERAMICA",
    label: "TÉCNICO EN CERAMICA",
  },
  {
    value: "TÉCNICO EN BENEFICIO Y TRANSFORMACION DE ARCILLAS",
    label: "TÉCNICO EN BENEFICIO Y TRANSFORMACION DE ARCILLAS",
  },
  {
    value: "TÉCNICO EN PRODUCCIÓN DE BIOCOMBUSTIBLES Y FERMENTACIONES INDUSTRIALES",
    label: "TÉCNICO EN PRODUCCIÓN DE BIOCOMBUSTIBLES Y FERMENTACIONES INDUSTRIALES",
  },
  {
    value: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR INYECCION",
    label: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR INYECCION",
  },
  {
    value: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR SOPLADO",
    label: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR SOPLADO",
  },
  {
    value: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR EXTRUSION DE PELICULA",
    label: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR EXTRUSION DE PELICULA",
  },
  {
    value: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR EXTRUSION DE PERFILES",
    label: "TÉCNICO EN TRANSFORMACION DE POLIMEROS POR EXTRUSION DE PERFILES",
  },
  {
    value: "TÉCNICO EN EXTRUSION DE PLASTICOS",
    label: "TÉCNICO EN EXTRUSION DE PLASTICOS",
  },
  {
    value: "TÉCNICO EN RECUPERACION DE RESIDUOS SOLIDOS PLASTICOS",
    label: "TÉCNICO EN RECUPERACION DE RESIDUOS SOLIDOS PLASTICOS",
  },
  {
    value: "TÉCNICO EN TRATAMIENTO DE AGUA",
    label: "TÉCNICO EN TRATAMIENTO DE AGUA",
  },
  {
    value: "TÉCNICO EN OPERACIÓN DE SISTEMAS DE TRATAMIENTO DE VERTIMIENTOS LÍQUIDOS",
    label: "TÉCNICO EN OPERACIÓN DE SISTEMAS DE TRATAMIENTO DE VERTIMIENTOS LÍQUIDOS",
  },
  {
    value: "TECNÓLOGO EN RIEGO, DRENAJE Y MANEJO DE SUELOS AGRÍCOLAS",
    label: "TECNÓLOGO EN RIEGO, DRENAJE Y MANEJO DE SUELOS AGRÍCOLAS",
  },
  {
    value: "TÉCNICO EN ELABORACION DE OBJETOS ARTESANALES CON FIBRAS TEXTILES",
    label: "TÉCNICO EN ELABORACION DE OBJETOS ARTESANALES CON FIBRAS TEXTILES",
  },
  {
    value: "TÉCNICO EN TEJEDURIA EN TELAR PARA PRODUCTOS ARTESANALES",
    label: "TÉCNICO EN TEJEDURIA EN TELAR PARA PRODUCTOS ARTESANALES",
  },
  {
    value: "TÉCNICO EN TINTORERIA Y ACABADOS TEXTILES",
    label: "TÉCNICO EN TINTORERIA Y ACABADOS TEXTILES",
  },
  {
    value: "TECNÓLOGO EN QUÍMICO TEXTIL",
    label: "TECNÓLOGO EN QUÍMICO TEXTIL",
  },
  {
    value: "TÉCNICO EN TRAZO Y CORTE INDUSTRIAL DE MATERIAL TEXTIL",
    label: "TÉCNICO EN TRAZO Y CORTE INDUSTRIAL DE MATERIAL TEXTIL",
  },
  {
    value: "TÉCNICO EN MANUFACTURA DE PRODUCTOS EN CUERO CON TECNICAS MANUALES",
    label: "TÉCNICO EN MANUFACTURA DE PRODUCTOS EN CUERO CON TECNICAS MANUALES",
  },
  {
    value: "TÉCNICO EN FABRICACION INDUSTRIAL DE MARROQUINERIA",
    label: "TÉCNICO EN FABRICACION INDUSTRIAL DE MARROQUINERIA",
  },
  {
    value: "TÉCNICO EN CUSTOMIZACION DE CALZADO",
    label: "TÉCNICO EN CUSTOMIZACION DE CALZADO",
  },
  {
    value: "TÉCNICO EN PRODUCCION DE CALZADO.",
    label: "TÉCNICO EN PRODUCCION DE CALZADO.",
  },
  {
    value: "TÉCNICO EN GUARNICION DE CALZADO",
    label: "TÉCNICO EN GUARNICION DE CALZADO",
  },
  {
    value: "TÉCNICO EN MONTAJE INDUSTRIAL DE CALZADO",
    label: "TÉCNICO EN MONTAJE INDUSTRIAL DE CALZADO",
  },
  {
    value: "TÉCNICO EN CONTROL DE CALIDAD EN CONFECCION INDUSTRIAL",
    label: "TÉCNICO EN CONTROL DE CALIDAD EN CONFECCION INDUSTRIAL",
  },
  {
    value:
      "TÉCNICO EN CONFECCION INDUSTRIAL DE PRENDAS DE VESTIR APLICANDO HERRAMIENTAS DE PRODUCTIVIDAD",
    label:
      "TÉCNICO EN CONFECCION INDUSTRIAL DE PRENDAS DE VESTIR APLICANDO HERRAMIENTAS DE PRODUCTIVIDAD",
  },
  {
    value: "TÉCNICO EN CONTROL DE CALIDAD EN CALZADO Y MARROQUINERIA.",
    label: "TÉCNICO EN CONTROL DE CALIDAD EN CALZADO Y MARROQUINERIA.",
  },
  {
    value: "TÉCNICO EN CLASIFICACION DE PIELES Y CUEROS",
    label: "TÉCNICO EN CLASIFICACION DE PIELES Y CUEROS",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE FRUTAS Y HORTALIZAS",
    label: "TÉCNICO EN PROCESAMIENTO DE FRUTAS Y HORTALIZAS",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE FRUTAS Y HORTALIZAS",
    label: "TÉCNICO EN PROCESAMIENTO DE FRUTAS Y HORTALIZAS",
  },
  {
    value: "TÉCNICO EN OPERACION DE BIORREACTORES",
    label: "TÉCNICO EN OPERACION DE BIORREACTORES",
  },
  {
    value: "TÉCNICO EN CHOCOLATERIA..",
    label: "TÉCNICO EN CHOCOLATERIA..",
  },
  {
    value: "TÉCNICO EN ELABORACION DE PRODUCTOS ALIMENTICIOS.",
    label: "TÉCNICO EN ELABORACION DE PRODUCTOS ALIMENTICIOS.",
  },
  {
    value: "TÉCNICO EN AGROINDUSTRIA ALIMENTARIA",
    label: "TÉCNICO EN AGROINDUSTRIA ALIMENTARIA",
  },
  {
    value: "TÉCNICO EN AGROINDUSTRIA PANELERA",
    label: "TÉCNICO EN AGROINDUSTRIA PANELERA",
  },
  {
    value: "TÉCNICO EN ALISTAMIENTO Y OPERACIÓN DE MAQUINARIA PARA LA PRODUCCIÓN INDUSTRIAL",
    label: "TÉCNICO EN ALISTAMIENTO Y OPERACIÓN DE MAQUINARIA PARA LA PRODUCCIÓN INDUSTRIAL",
  },
  {
    value:
      "TECNÓLOGO EN TRANSFORMACIÓN DEL CACAO Y ELABORACIÓN DE PRODUCTOS DE CHOCOLATERÍA INDUSTRIAL",
    label:
      "TECNÓLOGO EN TRANSFORMACIÓN DEL CACAO Y ELABORACIÓN DE PRODUCTOS DE CHOCOLATERÍA INDUSTRIAL",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE LACTEOS",
    label: "TÉCNICO EN PROCESAMIENTO DE LACTEOS",
  },
  {
    value: "TÉCNICO EN ELABORACION DE PRODUCTOS DE CONFITERIA",
    label: "TÉCNICO EN ELABORACION DE PRODUCTOS DE CONFITERIA",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE CARNES",
    label: "TÉCNICO EN PROCESAMIENTO DE CARNES",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO DE DERIVADOS LACTEOS.",
    label: "TÉCNICO EN PROCESAMIENTO DE DERIVADOS LACTEOS.",
  },
  {
    value: "TÉCNICO EN CERVECERIA ARTESANAL",
    label: "TÉCNICO EN CERVECERIA ARTESANAL",
  },
  {
    value: "TÉCNICO EN IMPRESION OFFSET",
    label: "TÉCNICO EN IMPRESION OFFSET",
  },
  {
    value: "TÉCNICO EN IMPRESIÓN SERIGRÁFICA",
    label: "TÉCNICO EN IMPRESIÓN SERIGRÁFICA",
  },
  {
    value: "TÉCNICO EN IMPRESIÓN FLEXOGRÁFICA",
    label: "TÉCNICO EN IMPRESIÓN FLEXOGRÁFICA",
  },
  {
    value: "TÉCNICO EN PREPRENSA DIGITAL PARA MEDIOS IMPRESOS",
    label: "TÉCNICO EN PREPRENSA DIGITAL PARA MEDIOS IMPRESOS",
  },
  {
    value: "TÉCNICO EN ACABADOS ESPECIALES DE DOCUMENTOS IMPRESOS",
    label: "TÉCNICO EN ACABADOS ESPECIALES DE DOCUMENTOS IMPRESOS",
  },
  {
    value: "TÉCNICO EN ENSAMBLE DE VEHICULOS AUTOMOTORES",
    label: "TÉCNICO EN ENSAMBLE DE VEHICULOS AUTOMOTORES",
  },
  {
    value: "TÉCNICO EN ENSAMBLE DE VEHICULOS",
    label: "TÉCNICO EN ENSAMBLE DE VEHICULOS",
  },
  {
    value: "TÉCNICO EN ENSAMBLE DE COMPONENTES PARA AUTOMOTORES",
    label: "TÉCNICO EN ENSAMBLE DE COMPONENTES PARA AUTOMOTORES",
  },
  {
    value: "TÉCNICO EN FABRICACIÓN DE MUEBLES CONTEMPORÁNEOS Y MODULARES",
    label: "TÉCNICO EN FABRICACIÓN DE MUEBLES CONTEMPORÁNEOS Y MODULARES",
  },
  {
    value: "TÉCNICO EN EBANISTERIA.",
    label: "TÉCNICO EN EBANISTERIA.",
  },
  {
    value: "TÉCNICO EN FABRICACION Y MANTENIMIENTO DE PRODUCTOS CON MATERIALES COMPUESTOS",
    label: "TÉCNICO EN FABRICACION Y MANTENIMIENTO DE PRODUCTOS CON MATERIALES COMPUESTOS",
  },
  {
    value: "TÉCNICO EN PRODUCCIÓN CON POLIÉSTER REFORZADO",
    label: "TÉCNICO EN PRODUCCIÓN CON POLIÉSTER REFORZADO",
  },
  {
    value: "TÉCNICO EN RECUBRIMIENTOS METALICOS",
    label: "TÉCNICO EN RECUBRIMIENTOS METALICOS",
  },
  {
    value: "TÉCNICO EN PINTURA INDUSTRIAL PARA MOBILIARIO EN MADERA",
    label: "TÉCNICO EN PINTURA INDUSTRIAL PARA MOBILIARIO EN MADERA",
  },
  {
    value: "TÉCNICO EN RECUBRIMIENTO CON PINTURA PARA EQUIPOS DE TRANSPORTE.",
    label: "TÉCNICO EN RECUBRIMIENTO CON PINTURA PARA EQUIPOS DE TRANSPORTE.",
  },
  {
    value: "TÉCNICO EN PROCESAMIENTO Y CARACTERIZACION DE MATERIALES METALICOS",
    label: "TÉCNICO EN PROCESAMIENTO Y CARACTERIZACION DE MATERIALES METALICOS",
  },
];
